### ISSUE TITLE
performance difference between windows and unix version

### ISSUE THREAD

**Issue by fishman2008** [AlexeyAB/darknet#105]
I have trained the model using the unix version which is provided by original author. And then the outputs are compared between the windows and unix versions. It appears that the windows version provides less accurate results than the original one. I used the default sets of parameters for comparison. For instance, the windows version may miss some detections, whereas the unix version correctly locates the subject. 

Thanks for your clarification.

**Comment by AlexeyAB** [comment]
@fishman2008 What initial .cfg-files did you use on Linux and Windows for training? 

* `yolo-voc.2.0.cfg` or `yolo-voc.cfg`?
* Did you use the same .cfg-files on Linux and Windows, or different?

**Comment by fishman2008** [comment]
I use yolo-voc.2.0.cfg. It should be the same cfg-files for both linux and windows. I did notice some performance differences between these two. No parameters have been modified such as the threshold. They are tested on individual samples.

**Comment by AlexeyAB** [comment]
This Windows-fork of Darknet-Yolo is based on commit Nov 27, 2016. So after this time some improvements of training were made in Linux-version, which I didn't merge to this fork yet.

But also, it can be just a fluctuation in accuracy.

----

Also you can get different outputs of `darknet.exe detector recall ...`, because:
*  I increase threshold to `0.2`: https://github.com/AlexeyAB/darknet/blame/b585124e55fcd18a7511d3b2fdc6bc3db5368ef4/src/detector.c#L387
* And change calculation of IoU: https://github.com/AlexeyAB/darknet/blame/b585124e55fcd18a7511d3b2fdc6bc3db5368ef4/src/detector.c#L419
