### ISSUE TITLE
only person label showing on trained weights

### ISSUE THREAD

**Issue by thriskel** [AlexeyAB/darknet#1083]
following github instructions on training custom objects I trained my data until 14000.  While checking the predictions on new images, it gets the object that I trained it for but labels it as "person" this not being part of the labels I wrote down on the obj.names file.

**Comment by AlexeyAB** [comment]
* What command do you use for detection?
* Show your obj.data and obj.names files.

**Comment by thriskel** [comment]
I'm using the following command for detection:

> darknet.exe detect yolo-obj.cfg backup/yolo-obj_15352.weights data/image.jpg

here are the files.
[obj.data.txt](https://github.com/AlexeyAB/darknet/files/2127547/obj.data.txt)
[obj.names.txt](https://github.com/AlexeyAB/darknet/files/2127548/obj.names.txt)

**Comment by thriskel** [comment]
just realized this, why is it looking into coco.names? 
`Error: in the file data/coco.names number of names 80 that isn't equal to classes=2 in the file cfg/coco.data`

**Comment by AlexeyAB** [comment]
As said here, you should use such command:
`darknet.exe detector test data/obj.data yolo-obj.cfg yolo-obj_8000.weights`


I.e. use `darknet.exe  detector test data/obj.data` instead of `darknet.exe detect`

----

https://github.com/AlexeyAB/darknet#how-to-use-on-the-command-line

> Yolo v3 COCO - image: darknet.exe detector test data/coco.data cfg/yolov3.cfg yolov3.weights -i 0 -thresh 0.25
> Alternative method Yolo v3 COCO - image: darknet.exe detect cfg/yolov3.cfg yolov3.weights -i 0 -thresh 0.25

It means that these 2 command are equal, so actually you use command with `coco.names`:
`darknet.exe detector test data/coco.data yolo-obj.cfg backup/yolo-obj_15352.weights data/image.jpg`
