### ISSUE TITLE
coding style tabs/spaces

### ISSUE THREAD

**Issue by tinohager** [AlexeyAB/darknet#1169]
Which one is the standard for this project?

**Comment by AlexeyAB** [comment]
By default were used 4 spaces for indents. 

----

So I just fixed it to use spaces: https://github.com/AlexeyAB/darknet/commit/cfc5fedbb6df2471493b1ec162d0024485618211

And added configuraion for EditorConfig plugin for MSVS: https://marketplace.visualstudio.com/items?itemName=EditorConfigTeam.EditorConfig
to use 4 spaces for indents instead of tab: https://github.com/AlexeyAB/darknet/blob/cfc5fedbb6df2471493b1ec162d0024485618211/src/.editorconfig#L1-L6
It is required because in other projects I uses Tabs instead of Spaces, so I set global options in MSVS to use Tabs for indents.

**Comment by tinohager** [comment]
perfect! I like 4 spaces
