### ISSUE TITLE
print_network

### ISSUE THREAD

**Issue by sonalambwani** [AlexeyAB/darknet#1413]
Hi Alexey et al,
I have trained a yolo3 model on my own data and it works great. Could you help me understand something?
In test_detector(...), after passing the image through network_predict( ..), I tried printing the output of the network using print_network(net). 
The result was that for all layers, except the YOLO layers, the output was 0.0. This is what I dont understand. As the image forward props through each layer, I'd have expected to get non-zero layer outputs.

As I mentioned before, the results of bounding boxes is great.

Thanks,
Sonal

**Comment by AlexeyAB** [comment]
@sonalambwani Hi,


Just add before this line: https://github.com/AlexeyAB/darknet/blob/7f9145729c2a2b64a7aeb3806f7c3d21771fce94/src/network.c#L718
such line: 
```
#ifdef GPU
cuda_pull_array(l.output_gpu, l.output, l.batch*l.outputs);
#endif
```


----

The reason:

`print_network(net)` prints only from CPU-memory: https://github.com/AlexeyAB/darknet/blob/7f9145729c2a2b64a7aeb3806f7c3d21771fce94/src/network.c#L713-L728

Since function doesn't download results from l.output_gpu to l.output (only [yolo] and [region] layers download results to CPU): https://github.com/AlexeyAB/darknet/blob/7f9145729c2a2b64a7aeb3806f7c3d21771fce94/src/network_kernels.cu#L47-L77

**Comment by sonalambwani** [comment]
Thanks! that explains it.
