### ISSUE TITLE
Why does decreasing the number of filters in a layer increases the inference time?

### ISSUE THREAD

**Issue by kssk16** [AlexeyAB/darknet#1536]
Hi,
I have decreased the number of filters in a convolution layer from 64 to 32 and also the number of channels for each filter in the next convolution layer from 64 to 32. But I see a slight increase in inference time than decreasing? Does anyone have any idea about this?

**Comment by AlexeyAB** [comment]
@kssk16 Hi,

* Can you provide your cfg-file?

* Do you use CUDA and cuDNN?

* What is the `Total BFLOPS` did you get before your changes and after your changes?

* What time did you get before your changes and after your changes?

**Comment by kssk16** [comment]
@AlexeyAB  Thank you for your response.

[yolov3_cfg.txt](https://github.com/AlexeyAB/darknet/files/2351700/yolov3_cfg.txt)

Question: Do you use CUDA and cuDNN?
Yes, I use both CUDA and cuDNN.

Question: What is the Total BFLOPS did you get before your changes and after your changes?
before changes: 65.864
after changes: 64.978

Question: What time did you get before your changes and after your changes?
The time is changing dynamically, between 27ms to 32 ms.

On a side note, I might be wrong on my observation that inference time increases after decreasing the number of filters. Since the decrease in FLOPS is not much I might not be seeing a significant decrease in inference time. COuld you confirm on this?

**Comment by AlexeyAB** [comment]
Yes, there shouldn't be significant time decreasing, since BFLOPS is decreased only by 1%.
For more clean experiment - you should make several experiments and average execution time.
Theoretically some algorithms can work slow for small tensors (low number of filters or channels), but I don't think that this is the case.

Default yolov3.cfg:
![image](https://user-images.githubusercontent.com/4096485/45087144-9eb2a880-b10d-11e8-9ef6-79e88ac1740f.png)

Your yolov3.cfg:
![image](https://user-images.githubusercontent.com/4096485/45087165-a70ae380-b10d-11e8-9e1d-aa78cb62c02f.png)




If you want increase speed, you should change BFLOPS at least twice. So look at the Yolo output to understand what layers should be optimized.
