### ISSUE TITLE
yolo_cpp_dll gives different inference times for inference on the same image

### ISSUE THREAD

**Issue by AyushP123** [AlexeyAB/darknet#1615]
Hi,
    I have observed that if I run an image through a darknet graph using yolo_cpp_dll multiple times, I get different inference times for each run. Wanted to know if there is an explanation for this ( its concerning as the first iteration takes significantly more time than the others ).
```
#include <darknet/yolo_v2_class.hpp>
#include <iostream>
#include <ctime>

using namespace std;
int main()
{
    Detector abc("tiny_yolo_v2.cfg", "tiny_yolo_v2.weights");
    double total_time= 0;
    for(int i = 0; i < 10; i++)
    {
        clock_t start = clock();
        vector<bbox_t> boxes = abc.detect("1.png");
        clock_t end = clock();
        double temp_time = (end - start) / (double)CLOCKS_PER_SEC;
        total_time += temp_time;
        cout << temp_time << endl;
    }
    cout << "Time taken for forward pass: " << ten_times / 10 ;
    return 0;
}
```

Here is the output:

0.212
0.032
0.035
0.034
0.033
0.036
0.045
0.037
0.032
0.037
Time taken for forward pass: 0.0533

**Comment by AlexeyAB** [comment]
@AyushP123 Hi,

`clock_t start = clock();` it is a bad timer, because it can measure CPU-time instead of actual time. It behaves differently with a different number of threads on different OSs:  https://stackoverflow.com/questions/38252022/does-standard-c11-guarantee-that-high-resolution-clock-measure-real-time-non

Use `std::chrono::steady_clock` instead of `clock()`: https://en.cppreference.com/w/cpp/chrono/steady_clock

----

Also what params do you use in the Makefile?
What GPU do you use?
What OS do you use?

**Comment by AyushP123** [comment]
Hi,
    Thanks for your response. Using std::chrono::steady_clock led to the following results which are consistent:

31.2893
30.8513
31.147
31.1005
30.5459
30.7645
30.8974
31.3467
31.0775
31.3535

OS: Windows
GPU: NVIDIA GEFORCE 940 MX
yolo_cpp_dll build with CUDA 9.1 and without OpenCV.

**Comment by erlendhade** [comment]
Hi @AyushP123 

Have you been able to use the shared library for detection on webcam video?
I have been trying to get it to work: #1629 
My code runs, and the GPU seems to be crunching numbers, but bboxes or detections are being displayed..

**Comment by AyushP123** [comment]
I have been able to use shared library for other purposes. I have built yolo_cpp_dll for my purpose.
