### ISSUE TITLE
Check this improvment

### ISSUE THREAD

**Issue by vinjn** [AlexeyAB/darknet#1689]
https://github.com/pjreddie/darknet/pull/1130

**Comment by AlexeyAB** [comment]
Thanks. But it doesn't make sense for this repository, since there is already more faster improvement - `fuse_conv_batchnorm(net);` that removes batch-normalization layer at all for forward inference, so we shouldn't accelerate it. It is faster than this fix https://github.com/pjreddie/darknet/pull/1130

 https://github.com/AlexeyAB/darknet/blob/c02216120ba3e03ec74f8194ab72b47559f0638d/src/network.c#L814-L850

**Comment by vinjn** [comment]
Awesome, I will close it :)
