### ISSUE TITLE
 If error occurs - run training with flag: -dont_show

### ISSUE THREAD

**Issue by yangyangyang1278** [AlexeyAB/darknet#1746]
i want to train my own model, but when i start to train, the console shows " If error occurs - run training with flag: -dont_show" and then my training stops. Can you help me?

**Comment by yangyangyang1278** [comment]
![image](https://user-images.githubusercontent.com/44047616/46780923-a2130280-cd51-11e8-8c1c-77c2a1c490bd.png)

**Comment by yangyangyang1278** [comment]
sorry to bother， i have found y. the reason is that my train.txt file is empty

**Comment by liangxi627** [comment]
hello, @yangyangyang1278 ,my train.txt file is not empty, and the training path is correct , but I still meet this error, how to solve it?

**Comment by PiseyYou** [comment]
because you are using the final weight but not the pretrain model, the final weight had already got the classify and not match the type as your own dataset. Try to get the pretrain model as the following command, the path point where your pan.weights located.
`./darknet partial tiny_relate/pan/yolo_v3_tiny_pan2.cfg tiny_relate/pan/yolov3-tiny_pan.weights tiny_relate/pan/yolov3-tiny_pan.conv.44 44`
after get the pretrain model, and set the yolo type num and filter, you can train now.
