### ISSUE TITLE
Problems in training

### ISSUE THREAD

**Issue by HUNGLiquid** [AlexeyAB/darknet#1827]
@AlexeyAB Hi , I have a problem. When i'm training yolo2 with my custom objects. The avg loss is 
fluctuated around 1-0.6 (3000 iterations). What can i do to improve this situation.
 I fixed cfg-file :
//3 batch=64
//4 subdivisions=32
//237 filters=55
//242 anchors =  14.3685,25.8547, 31.5603,34.1492, 38.6145,91.2432, 55.5591,127.8102,45.8894,159.3808
//244 classes=6
With anchors calculate:
![image](https://user-images.githubusercontent.com/32360741/47601683-7012c900-d9fe-11e8-95fd-c5d93905c33e.png)
And avgloss:
![image](https://user-images.githubusercontent.com/32360741/47601724-f62f0f80-d9fe-11e8-83fe-d9c3eb9f3ba6.png)

**Comment by AlexeyAB** [comment]
@HUNGLiquid 

If you train yolov2.cfg instead of yolov3.cfg, then 

* either you should use default anchors: https://github.com/AlexeyAB/darknet/blob/31df5e27356b6b11ffd43baace9afdd3800a8aa2/cfg/yolov2.cfg#L242

* or you should calculate them by using such command
`./darknet detector calc_anchors data/obj.data -num_of_clusters 5 -width 13 -height 13`

**Comment by HUNGLiquid** [comment]
@AlexeyAB Thank you. Why use "-width 13 -height 13" when the net size is 416?
One more thing. When I try to use yolov3cfg, it runs about 10 min after that the console cancels.
The subdivisions = 64. Does GPU out memory?
