### ISSUE TITLE
darknet.exe

### ISSUE THREAD

**Issue by 89douner** [AlexeyAB/darknet#1858]
I started to use alexeyAB/darknet. So, I have some questions.

Q1. Is there darknet.exe file in this version? I can't see the file, but can see darknet.exe in official version. How do I get darknet.exe file?

Q2. Does this version support cuda9.0? I just copy darknet.exe from official version to this version. After running train-command as below figure, then I had error. 

![bbb](https://user-images.githubusercontent.com/31752297/47771080-3bb44b00-dd25-11e8-8ba8-6b82a0c883ba.png)
![aaa](https://user-images.githubusercontent.com/31752297/47771048-158eab00-dd25-11e8-831c-77837ec74e3c.png)
![ccc](https://user-images.githubusercontent.com/31752297/47771200-abc2d100-dd25-11e8-95bf-3b192963ee07.png)

**Comment by AlexeyAB** [comment]
> Q1. Is there darknet.exe file in this version? I can't see the file, but can see darknet.exe in official version. How do I get darknet.exe file?

You should do command `make` to compile. It will create executable file `./darknet`

(official version doesn't have `darknet.exe` since `darknet.exe` is executable file on Windows only, and only this version supports Windows OS.)

> Q2. Does this version support cuda9.0? I just copy darknet.exe from official version to this version. After running train-command as below figure, then I had error.

Yes.

This repository supports:

both Windows and Linux
both OpenCV 2.x.x and OpenCV <= 3.4.0 (3.4.1 and higher isn't supported)
both cuDNN >= v5
CUDA >= 7.5
also create SO-library on Linux and DLL-library on Windows

**Comment by 89douner** [comment]
Thanks! I solved!
