### ISSUE TITLE
How to limit GPU memory?

### ISSUE THREAD

**Issue by K0307** [AlexeyAB/darknet#190]
I want to run two YOLO darknet processes simultaneously . But I am getting CUDA memory error while running second process. So how can I allocate memory to each darknet process like tensorflow (per_process_gpu_memory_fraction=0.18)

**Comment by AlexeyAB** [comment]
Yolo is system for realtime detection, so it itself decides how much memory to occupy on GPU for speedup - to avoid multiple unnecessary copying of data between CPU<->GPU.

You can make Yolo use less memory:
* set `batch=1` `subdivison=1` in cfg file
* use `tiny-yolo-voc.cfg` instead of `yolo-voc.cfg`
