### ISSUE TITLE
Dear, Sir.

### ISSUE THREAD

**Issue by richardminh** [AlexeyAB/darknet#2025]
Hello, how are u?
I am a student, and I received an homework to write an vehicle logo detection program. After working with the literature, I found that using your method would yield the highest performance.
But I'm afraid I would get high performance in a limited amount of time.
Are you experienced with vehicle logo detection? I think you have a great experiences in object detection and recogition. Can you provide pre-learned models as you are a great expert in YOLO?　
I will take you as a teacher.
Then, thanks very much !!!!!!!!
Thanks and Best regards, RichardMinh.

**Comment by isgursoy** [comment]
So cute. You made my day :)

**Comment by richardminh** [comment]
Thanks for your reply. Can you help me, sir?

**Comment by isgursoy** [comment]
I am not aware of any pretrained models for vehicle logo detection. May be this one: https://gist.github.com/bogger/b90eb88e31cd745525ae
Probably you should train yourself. Prepare your dataset, follow instructions in wiki and make sure you read enough before bringing your question here.
______________________________________________________________________________
This repo is for yolo itself and there are general purpose models around to show how it works. Better looking for a "Vehicle Logo Detection" repo and asking for model there. Your problem is not related with yolo.

Problem here is the way you opened this issue. Title should be clear single short sentence summary of your problem, you should cut how are you part and any other emotional things in description.

**Comment by isgursoy** [comment]
+ good to close issue when you are done, so you can help maintaining issue reports.
