### ISSUE TITLE
TRACK_OPTFLOW is based on GPU？

### ISSUE THREAD

**Issue by zhongjiejiang** [AlexeyAB/darknet#2042]
AlexeyAB，

I want to know if the object tracking must be base on the CUDA env?

Thanks

**Comment by AlexeyAB** [comment]
@zhongjiejiang 

If `GPU` is defined then it uses GPU (also OpenCV should be compiled with CUDA): https://github.com/AlexeyAB/darknet/blob/3969ce30ed61651a63193b763f9914bd9953bbfd/src/yolo_v2_class.hpp#L167-L343

Otherwise it uses CPU: https://github.com/AlexeyAB/darknet/blob/3969ce30ed61651a63193b763f9914bd9953bbfd/src/yolo_v2_class.hpp#L343-L459

**Comment by zhongjiejiang** [comment]
thank u
