### ISSUE TITLE
.txt output

### ISSUE THREAD

**Issue by dascar5** [AlexeyAB/darknet#2049]
Just wondering if its possible to have the detection results print themselves to an external text file. Ideally, I would let the IP cam run in real time, with detection results updating live on (maybe a website), but I figure that's a stretch probably. If you knew how to just output it tho, that would be great. 
Also, is it possible to filter the output, or even the algorithm itself, so it only recognizes cars? I guess that's way harder to perform, but it would be a lot less taxing on the hardware.

**Comment by dascar5** [comment]
> > detection results print themselves to an external text file.
> 
> `./darknet detector demo cfg/coco.data yolov3.cfg yolov3.weights -ext_output http://192.168.0.80:8080/video?dummy=param.mjpg | tee result.txt`
> 
> Results will be in the `result.txt` file
> 
> > is it possible to filter the output, or even the algorithm itself, so it only recognizes cars?
> 
> Change this line:
> 
> [darknet/src/image.c](https://github.com/AlexeyAB/darknet/blob/f0bed8ef735f03e4d2ccbed9d1683b4f63043f44/src/image.c#L504)
> 
> Line 504 in [f0bed8e](/AlexeyAB/darknet/commit/f0bed8ef735f03e4d2ccbed9d1683b4f63043f44)
> 
>  if (class_id >= 0) { 
> 
> to this
> `if (class_id == 2) {`

Sorry to reopen it like this, I just tested the tee results.txt command but it did not work, it just crashes cmd, but it works without it. Also, pause command is not working for some reason.

**Comment by AlexeyAB** [comment]
@dascar5 

On Windows:

* or download `wtee` instead of `tee`: https://code.google.com/archive/p/wintee/downloads
and use `./darknet detector demo cfg/coco.data yolov3.cfg yolov3.weights -ext_output http://192.168.0.80:8080/video?dummy=param.mjpg | wtee result.txt`

* or use `>` instead of `tee`
`./darknet detector demo cfg/coco.data yolov3.cfg yolov3.weights -ext_output http://192.168.0.80:8080/video?dummy=param.mjpg > result.txt`
