### ISSUE TITLE
Couldn't open file: backup/cfg\yolo-obj_100.weights

### ISSUE THREAD

**Issue by JPatricio** [AlexeyAB/darknet#212]
Hi,

I'm training Yolo with a custom dataset and everything seems to be going well up to the point where it needs to save the first batch of trained weights on the 100th iteration.

Saving weights to backup/cfg\yolo-obj_100.weights
Couldn't open file: backup/cfg\yolo-obj_100.weights

I'm running this on windows so I thought clearly the problems lies with that incorrect forward slash, which I thought I might've wrongly placed in the configuration files. However, my obj.data files looks like this:
 
> classes= 1
> train  = data/001/train.txt
> valid  = data/001/test.txt
> names = obj.names
> backup = backup

I have no idea where he is getting that forward slash from since it's not explicitly written in the .data file. After a second look I was even more bewildered over the fact that the path to the train and test files are using a forward slash convention, but he was still able to find them anyway.

Anyone with any clue of what might be happening here? Could the forward slash be somehow hardcoded into the code? But then surely someone else would've run into this issue already

Thanks in advance

Edit: I found some other examples and apparently that "cfg\" shouldn't be there at all. But I have never explicitly specified that path.

**Comment by AlexeyAB** [comment]
Hi, **don't use `\` in the path of cfg file.** But you can use `/` in path of cfg file.

Use this command line `darknet.exe detector train data/obj.data yolo-obj.cfg darknet19_448.conv.23` instead of this `darknet.exe detector train data/obj.data cfg\yolo-obj.cfg darknet19_448.conv.23`

Or can use this: `darknet.exe detector train data/obj.data cfg/yolo-obj.cfg darknet19_448.conv.23`

**Comment by JPatricio** [comment]
Awesome! 

That worked, thanks for the fix!
