### ISSUE TITLE
detect imageData data returns -1

### ISSUE THREAD

**Issue by receptanilcengiz** [AlexeyAB/darknet#2214]
Hi @AlexeyAB 

using yolo_cpp_dll c# winform app, I am exactly doing same with yolowrapper.cs but "DetectImageGpu(pnt, imageData.Length, ref container);" return -1. where am I wrong?

```c#
private void button4_Click(object sender, EventArgs e)
{
            using (MemoryStream ms = new MemoryStream())
            {
                pictureBox1.Image.Save(ms, ImageFormat.Jpeg);
                Detect(ms.ToArray());
            }
}

public void Detect(byte[] imageData)
{
            var container = new BboxContainer();
            var size = Marshal.SizeOf(imageData[0]) * imageData.Length;
            var pnt = Marshal.AllocHGlobal(size);

                // Copy the array to unmanaged memory.
                Marshal.Copy(imageData, 0, pnt, imageData.Length);
                var count = 0;
                count = DetectImageGpu(pnt, imageData.Length, ref container);
                watch.Stop(); label2.Text = watch.Elapsed.TotalMilliseconds.ToString() + " ms";
}
```

**Comment by AlexeyAB** [comment]
@receptanilcengiz Hi,


You should compile `yolo_cpp_dll.sln` with OpenCV.
Otherwise it returns `-1` https://github.com/AlexeyAB/darknet/blob/920d792a0c34c70c722caf1db23792e81e51af5b/src/yolo_v2_class.cpp#L42-L53

----

Should be installed OpenCV: https://sourceforge.net/projects/opencvlibrary/files/opencv-win/3.3.0/opencv-3.3.0-vc14.exe/download

Open `build\darknet\yolo_cpp_dll.sln` in MSVS and do:

1. (right click on project) -> properties -> C/C++ -> Preprocessor -> Preprocessor Definitions - add `OPENCV;`

2. right click on project) -> properties -> C/C++ -> General -> Additional Include Directories, add: `C:\opencv_3.0\opencv\build\include;`

3. (right click on project) -> properties -> Linker -> General -> Additional Library Directories, add: `C:\opencv_3.0\opencv\build\x64\vc14\lib;`

Use paths where you has installed OpenCV.

**Comment by receptanilcengiz** [comment]
thank you so much SOLVED
