### ISSUE TITLE
Pure Testing Linux Laptop

### ISSUE THREAD

**Issue by daylanc** [AlexeyAB/darknet#2337]
Hi,

I have a Dell XPS laptop that I want use solely for testing purposes only. I will be doing the training on a Desktop computer with an NVIDIA Titan Xp GPU. I'm looking on the requirements section of the home page and see that I need CUDA 10.0 and OpenCV 3.3.0. If I am just using the laptop to test images, do I need CUDA and OpenCV? 
Basically, my plan is to train my network on the desktop computer, once finished, transfer the .weights file to my laptop so that I can test images with the portability of the laptop. What is the best way to go about installing darknet v3 on the laptop?

Thanks!

**Comment by Sauraus** [comment]
You do not need CUDA on the laptop, however `darknet` will use your CPU and be significantly slower because of that.

You also don't need openCV on your laptop, however this means you won't be able to actually see the images on your laptop and when you run `darknet detector test...` it will output a `predictions.png` instead.

**Comment by daylanc** [comment]
@Sauraus 
Thank you for your response. I believe this laptop does have a GPU, I just gotta figure out what it is. If I change the GPU to `GPU=1` in the makefile, will darknet be able to automatically use the GPU (if I have one on the laptop)?
