### ISSUE TITLE
train time too slow

### ISSUE THREAD

**Issue by derekwong66** [AlexeyAB/darknet#2546]
Hi, 

Thanks for your contribution. I met a problem which is training time too slow, roughly 15 second per iteration. I used 4 V100 GPUS and the detail is listed below. I trained yolov3_5l using conv74 pre-trained weight. Do u have any suggestion? Thanks in advance.
yolov3_5l.cfg
batch=64
subdivisions=8
width=416
height=416
channels=3
momentum=0.9
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1

learning_rate=0.00025
burn_in=4000
max_batches = 500200
policy=steps
steps=400000,450000
scales=.1,.1

32: 18097.035156, 18102.294922 avg loss, 0.000000 rate, 14.939995 seconds, 8192 images
Loaded: 0.000152 seconds
Region 82 Avg IOU: 0.364752, Class: 0.420356, Obj: 0.455260, No Obj: 0.528336, .5R: 0.500000, .75R: 0.000000,  count: 2
Region 82 Avg IOU: 0.254128, Class: 0.532054, Obj: 0.571704, No Obj: 0.528151, .5R: 0.000000, .75R: 0.000000,  count: 2
Region 94 Avg IOU: 0.303421, Class: 0.459461, Obj: 0.712428, No Obj: 0.518033, .5R: 0.333333, .75R: 0.000000,  count: 3
Region 82 Avg IOU: 0.326790, Class: 0.525718, Obj: 0.496520, No Obj: 0.528297, .5R: 0.000000, .75R: 0.000000,  count: 1
Region 82 Avg IOU: 0.306946, Class: 0.440138, Obj: 0.636802, No Obj: 0.528188, .5R: 0.000000, .75R: 0.000000,  count: 2
Region 94 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.518345, .5R: -nan, .75R: -nan,  count: 0
Region 94 Avg IOU: 0.405767, Class: 0.446331, Obj: 0.597845, No Obj: 0.518282, .5R: 0.200000, .75R: 0.000000,  count: 5
Region 94 Avg IOU: 0.496820, Class: 0.775144, Obj: 0.437980, No Obj: 0.518243, .5R: 0.333333, .75R: 0.333333,  count:

**Comment by yxwLearn** [comment]
@derekwong66 
Try to set bantch=64 and subvisions=16 or 32

**Comment by AlexeyAB** [comment]
@derekwong66 Hi,

Do you use Linux or Windows?

1. set `batch=64 subdivisions=4` in cfg-file. (if out of memory error occur, then set `subdivisions=8` or 16

2. Set `GPU=1 CUDNN=1 CUDNN_HALF=1 OPENCV=` in the `Makefile` and the recompile 
```
make clean
make
```

3. Run training by using command (flag `-dont_show` is necessary only if your server don't have connected monitor):
`./darknet detector train data/obj.data cfg/yolov3-obj.cfg darknet53.conv.74 -dont_show`

then after 1000 iterations, stop training and run this command:
`./darknet detector train data/obj.data cfg/yolov3-obj.cfg backup/yolov3-obj_1000.weights -dont_show -gpus 0,1,2,3`

If you will do all 3 steps - the training should go much more faster.


----

Also if you use your own server or DGX-1/2 instead of Amazon EC2, then you can set here `6` or `12` instead of `3` and recompile: https://github.com/AlexeyAB/darknet/blob/b751bac17505a742f149ada81d75689b5e692cde/src/detector.c#L173

**Comment by derekwong66** [comment]
I use Linux and our own server. I will try ur instruction. Thanks for ur reply.

**Comment by derekwong66** [comment]
hi @AlexeyAB 
I compiled darknet as you said. However, while training achieves 12000, Tensor core are used, the training process was stopped automatically.

**Comment by AlexeyAB** [comment]
@derekwong66 Hi,

* Do you use these params in cfg-file?
```
burn_in=4000
max_batches = 500200
```

* Do you use this params in makefile?  `GPU=1 CUDNN=1 CUDNN_HALF=1 OPENCV=1 AVX=0 DEBUG=0`

* Do you have any records in the files `bad.list` and `bad_label.list`?

* Can you continue training successfully? 
`./darknet detector train data/obj.data yolo-obj.cfg backup/yolo-obj_12000.weights -map`

* Can you show screenshot of this error?

**Comment by derekwong66** [comment]
burn_in=4000
max_batches = 200200
GPU=1 CUDNN=1 CUDNN_HALF=1 OPENCV=1 AVX=0 DEBUG=1
no bad.list and badlabel.list
no error showed, just stopped

if I set CUDNN_HALF= 0, it continues

**Comment by AlexeyAB** [comment]
@derekwong66 Use `DEBUG=0` too

**Comment by DarylWM** [comment]
Training yolov3_5l on my data set takes about 38 seconds per iteration on an AWS p3.2xlarge instance.

In my Makefile I have:
GPU=1
CUDNN=1
CUDNN_HALF=1
OPENCV=1
AVX=1
OPENMP=1
LIBSO=0
ZED_CAMERA=0

My images are 910x910 and I've set height,width to be 960,960. Batch is 64 and the lowest value for subdivisions I can use without running out of memory is 32.

I've disabled augmentation and set random=0.

**Comment by AlexeyAB** [comment]
@DarylWM 

> **Batch is 64** and the lowest value for **subdivisions** I can use without running out of memory is **32**.
> Training **yolov3_5l** on my data set takes about **38 seconds** per iteration on an AWS p3.2xlarge instance.

It should take about 10-20 sec.

How many iterations did you train? (the first 3000 iterations Tensor Cores will be disabled)

Did you check that this is not bottleneck on CPU? (for example leave only 4 images in `train.txt` and run training, how long does it take?)


> I've disabled augmentation and set random=0.

You can use random=0. But you can enable other data augmentation functions, I think it shouldn't affect on speed.

**Comment by DarylWM** [comment]
Hi @AlexeyAB .

I stopped it after 4800 iterations. It was taking about 33 seconds per iteration after 3000 iterations when the tensor cores were enabled.

With just 4 images in train.txt it still took ~37 seconds.

For the sake of comparison, training yolov3_5l also takes about 36 seconds per iteration on my 1070 (though that's with dimensions 896x896, batch=64, subdivisions=64).

**Comment by AlexeyAB** [comment]
@DarylWM 

> Edit: I also note (with nvidia-smi) the V100 cycles between near-100% and 0% utilisation every few seconds, so it doesn't seem to be GPU-bound either.

So, data augmentation on CPU is a bottleneck. 

Also low `mini_batch_size=batch/subdivisions` doesn't allow efficient use GPU(especially the TensorCores), since should be min_batch=16,32 or 64... (batch=64 subdivision=4,2 or 1) https://github.com/AlexeyAB/darknet/issues/407
That you can't set on yolov3_5l 960x960.

**Comment by DarylWM** [comment]
Hi @AlexeyAB .

> So, data augmentation on CPU is a bottleneck.

I believe I've turned off data augmentation because it doesn't make sense for my data set.
```
# angle=0
# saturation = 1.5
# exposure = 1.5
# hue=.1
flip=0
```
and `jitter=0`, `random=0`.

> should be min_batch=16,32 or 64...

To get mini-batch=16 (batch=64, subdivisions=4) for yolov3_5l on a V100 the images need to be 320x320. When I did that the GPU utilisation didn't seem to be higher; it was still varying evenly between near-100 and 0%. Is it just reflecting that for tensor cores the mini-batch should be higher? Iteration time came down to a few seconds though.

**Comment by AlexeyAB** [comment]
@DarylWM Hi,

GPU-utilization ~0% usually means that the bottleneck is on CPU. 
* If data augmentation is disabled, CPU still will be used for resizing images to the network size, and for converting from RGB(3xINT8) to RGB(3xFP32). 
* Also bottleneck may be in the `[yolo]`-layer that is processed on CPU.

----

Try to do:

1. I just added optimization when data augmentation is disabled (for OPENCV=1), so it should work slightly faster. Try to download the latest version.

2. Also you can try to set here `2` or `4`  instead of `3` and recompile: https://github.com/AlexeyAB/darknet/blob/8cd5a9364abc2afd753229b6291604132e625cc3/src/detector.c#L129
If it doesn't help, then set `3` again.

----

Just for comparison, try to train `yolov3.cfg` with `batch=64 subdivision=4 width=416 height=416 random=0` as here: https://github.com/AlexeyAB/darknet/issues/407
* do you get GPU-utilization ~0% sometimes?
* do you get iteration time ~1.27 seconds?
* what OpenCV version do you use?
