### ISSUE TITLE
No prediction with my trained model

### ISSUE THREAD

**Issue by langelesl** [AlexeyAB/darknet#2566]
Hi.

I trained a yolov3.weights on kitti dataset using pjreddie's darknet, which could output the prediction on images successfully. But when I used your repo to test the images with my weights, I got no error in loading the .weights file but also no prediction on image. I am not sure if something get wrong with my cfg or weights. Do I need to make any modification on .cfg file for using your darknet code to load the .weights?

**Comment by AlexeyAB** [comment]
@langelesl Hi,

Can you share your cfg and weights files, and the image for detection?

**Comment by langelesl** [comment]
Thank you for your fast reply. 

Sure, I have uploaded the weights, makefiles, cfg, file and data file I used [here](https://www.dropbox.com/sh/zv6h35190sa8e03/AABsf2LQuQHcuD2x3i8jzOLja?dl=0)
And I used the command "./darknet detector test ./cfg/kitti.data ./cfg/yolov3-kitti.cfg ./yolov3-kitti.weights data/kitti_img.png" for detection. Since my laptop is too old to get supports from cuda and cudnn, I am using cpu mode to run the compilation and detection. It caused a low speed but still could get the result using coco.data, original weights and cfg in your repo. But there was no results using my trained weights.

**Comment by langelesl** [comment]
And yes, I am using the latest version of your repository. I downloaded it today morning.

**Comment by AlexeyAB** [comment]
@langelesl 

Try to comment this line: https://github.com/AlexeyAB/darknet/blob/b751bac17505a742f149ada81d75689b5e692cde/src/detector.c#L1308

And un-comment this line: https://github.com/AlexeyAB/darknet/blob/b751bac17505a742f149ada81d75689b5e692cde/src/detector.c#L1310

----

For video:

Set there `1` instead of `0`: https://github.com/AlexeyAB/darknet/blob/b751bac17505a742f149ada81d75689b5e692cde/src/demo.c#L64

It is related to: https://github.com/AlexeyAB/darknet/issues/232#issuecomment-336955485

I will add flag for command to change resizing method from command line.

----

![predictions](https://user-images.githubusercontent.com/4096485/54078026-1dadb700-42d2-11e9-93bc-c1ab578c3655.jpg)

**Comment by langelesl** [comment]
Your suggestion works! Thank your very much for your helps.
