### ISSUE TITLE
Graphics Card

### ISSUE THREAD

**Issue by a23o** [AlexeyAB/darknet#26]
Hi guys!

I am going to buy an Nvidia GTX just to use this awsome build of darknet on windows. What would you reccomend? I am thinkig about 1060/1070/(1080). Budget is lower than the 1080's price, I am leaning towards the GTX 1070 but would be happy if the cheaper 1060 would be still okay. Is there anybody who has experience with said type of cards? What are you guys using? I will mostly do test (recognition), not so much traing. What kind of fps results can I expect with the COCO dataset? Do I have to be careful selecting a brand or card? Are there any issues with drivers, or Cuda8? As you can see, I am a bit lost here, so if you know a guide or a wiki, I would be glad for a link. 

Thx.

**Comment by wurstcase** [comment]
I got a 1070 and it works just fine. Getting somewhere around 50 to 60 fps on coco dataset.
Training is quite doable, trained a 2 class model with 8000 images over night with good results.

**Comment by VanitarNordic** [comment]
I have GTX 1060 (6G version by MSI ARMOR) and it works nice also, this last nVidia Pascal version of GPUs made the training and detection much faster. 

if you have money, go for 1070 because it is faster than GTX 1060 but 2G more memory in 1070 does not make that much difference except if you go for TITAN X Pascal with 12G memory.

Investing more money for overclocked GPUs of 1060/1070/1080 does not bring you more than 10% difference in performance at best if not less. Just pick up a standard model and invest that money somewhere else such as on RAM. 

GPU memory is number one factor in DNN training, the rest I can say influence training time and detection speed. My experience so far.

**Comment by a23o** [comment]
Thx for the input guys.
