### ISSUE TITLE
reference of *_no_gpu.sln have changed

### ISSUE THREAD

**Issue by WongKinYiu** [AlexeyAB/darknet#2684]
cuda.c => darknet_cuda.c
cuda.h => darknet_cuda.h

**Comment by AlexeyAB** [comment]
Yes, https://github.com/AlexeyAB/darknet/commit/685fae5feddd500514a513025d8886c07b6db5b8#diff-0c69c1fb81291d3e68b11a4cf2c05319R197
because cuda.c and cuda.h were renamed to dark_cuda.c and dark_cuda.h: https://github.com/AlexeyAB/darknet/commit/b6e15f16561c401c993092d180198555c1360cf7#diff-efbf95510aad9666ddb72811e6732b9e

To avoid confusing `cuda.h` from CUDA and `cuda.h` from Darknet.

**Comment by WongKinYiu** [comment]
thank you.

i download the repo at yesterday afternoon.
and it already fixed in current version.
https://github.com/AlexeyAB/darknet/commit/685fae5feddd500514a513025d8886c07b6db5b8
