### ISSUE TITLE
Legacy weights do not work with the latter changes in darknet

### ISSUE THREAD

**Issue by agirbau** [AlexeyAB/darknet#2688]
Hello!

I did a pull after a while (maybe 2 or 3 months), compiled (I tried both CMake and Make) and I'm not able to make it work with previous weight files (the program runs but nothing is detected).

If I train with this new pull it trains correctly and does correctly the detections.

Also in inference it is two times slower than the previous version.

Any wonder? I will compare both versions and check if I can find something. Thanks!

**Comment by agirbau** [comment]
I found the issue. These lines were commented recently:
https://github.com/AlexeyAB/darknet/blob/1cd332e4cac001ffcc12a24c72640fe02b69a8a0/src/parser.c#L1207-L1211
Do you recall why? 
Uncommenting these lines the speed is increased by a factor of 2, so the speed problem seems to be also problem of that issue?

Also I was wondering, Adam optimizer is used to train the network, but if I deactivate it in inference it doesn't detect the objects properly. Maybe somewhere in the code it is used for something else than training?

**Comment by AlexeyAB** [comment]
@agirbau To make it consistence with Original repository where is saving/loading current adam-values were removed:
* Read-adam: https://github.com/pjreddie/darknet/commit/1467621453e1c6932841a4992e6dffe0d0d8de24#diff-bfbbcdf73459e9ea8fb4afa8455ce74dL1071
* Save-adam: https://github.com/pjreddie/darknet/commit/1467621453e1c6932841a4992e6dffe0d0d8de24#diff-bfbbcdf73459e9ea8fb4afa8455ce74dL858

----

If you want to make old weights workable with the new repository, then you should:
* Temporary un-comment these lines: https://github.com/AlexeyAB/darknet/blob/1cd332e4cac001ffcc12a24c72640fe02b69a8a0/src/parser.c#L1207-L1211
* Set in your cfg-files `max_batches=1`
* Run training with `./darknet detector train obj.data yolov3_obj.cfg yolov3_obj_10000.weights` - so the final weights will be saved immideately without adam values, so you will can use it with new original and this repositories
(if some error with training data occurs, then set here `pthread_t load_thread;` instead of https://github.com/AlexeyAB/darknet/blob/9815012a01c13f70806381e0c5d556599117c76b/src/detector.c#L190 )

* do it for each required weights-file
* Comment these lines back: https://github.com/AlexeyAB/darknet/blob/1cd332e4cac001ffcc12a24c72640fe02b69a8a0/src/parser.c#L1207-L1211
* Use new weights-files.

**Comment by agirbau** [comment]
Thank you very much! 

I observed that if I don't specify "adam" in the config. file it also works.
