### ISSUE TITLE
Wrong Label : While Calculating Anchors

### ISSUE THREAD

**Issue by bhargavravat** [AlexeyAB/darknet#3006]
Hi @AlexeyAB  : 

Can you please explain the meaning of below attached screen shot? I am presently re calculating anchors before i run my training . 

![Screenshot from 2019-04-22 19-55-57](https://user-images.githubusercontent.com/11025174/56505363-14eb0a80-6539-11e9-991a-95559992aeff.png)

And below is the screen shot of the images which I have not labelled intentionally to do the negative training . 

![Screenshot from 2019-04-22 19-57-21](https://user-images.githubusercontent.com/11025174/56505386-2cc28e80-6539-11e9-842e-2c102e48762d.png)

Would be awaited for your inputs on the same.

**Comment by AlexeyAB** [comment]
@bhargavravat Hi,

1. Check your dataset by using Yolo_mark: https://github.com/AlexeyAB/Yolo_mark

2. Can you show content of some of these files? 
![Screenshot from 2019-04-22 19-55-57](https://user-images.githubusercontent.com/11025174/56505363-14eb0a80-6539-11e9-991a-95559992aeff.png)

----

3. And can you show content of some of these files? 

You should have empty txt-files instead of not having these files: https://github.com/AlexeyAB/darknet#how-to-improve-object-detection

> desirable that your training dataset include images with non-labeled objects that you do not want to detect - negative samples without bounded box (empty .txt files) - use as many images of negative samples as there are images with objects

![Screenshot from 2019-04-22 19-57-21](https://user-images.githubusercontent.com/11025174/56505386-2cc28e80-6539-11e9-842e-2c102e48762d.png)
