### ISSUE TITLE
OSError: ./libdarknet.so: cannot open shared object file

### ISSUE THREAD

**Issue by Arsiirasheed** [AlexeyAB/darknet#3013]
i have compiled the master branch and wheh i try to run dakrnet_video.py  it gives me the error

> OSError: ./libdarknet.so: cannot open shared object file

no such file exists for me 

i had made change as you mentioned in #2727 it genrate libdarklib.so not libdarknet.so

so should i change this line to libdarklib.so or is something else the solution

darknet.py
`else:
    lib = CDLL("./libdarknet.so", RTLD_GLOBAL)
lib.network_width.argtypes = [c_void_p]
lib.network_width.restype = c_int
lib.network_height.argtypes = [c_void_p]
lib.network_height.restype = c_int`

i have compiles with libso=1

**Comment by Christopheraburns** [comment]
When you ran make what was the final result?  Also, CDLL("./libdarknet.so") is looking for libdarknet.so in the same directory as the code that is calling it (Is this a line from darknet.py?),  I did not look at #2727, but if you generated a libdarklib.so and not a libdarknet.so - you need to update the line of code looking for libdarknet since it does not exist.

**Comment by Arsiirasheed** [comment]
got the file 
just run the command LD_LIBRARY_PATH=./:$LD_LIBRARY_PATH ./uselib ... and it produced libdarknet.so

**Comment by aimhabo** [comment]
@Arsiirasheed I added it before my bash command, but still got 'error while loading shared libraries: libdarknet.so: cannot open shared object file: No such file or directory'

**Comment by TiongSun** [comment]
before you compile, open Makefile and change "LIBSO=1"
After you compile, go to ur .py file and change the libdarknet.so to full path. Make sure that libdarknet.so is in the darknet folder. If not, compile again with libso = 1
