### ISSUE TITLE
demo video

### ISSUE THREAD

**Issue by johnnydept** [AlexeyAB/darknet#304]
Hi alex, I have been reading the codes for alwhile. I'm okay for most part of the image batch detection. But, i get super confused with the video detection (demo.c) . Alex can you kindly and briefly explain how the video detection part? Like how many thread it opened and what the thread been doing?

**Comment by AlexeyAB** [comment]
Hi, @johnnydept 

1. Defined 2 threads on CPU - for Yolo detection and for OpenCV video capture: https://github.com/AlexeyAB/darknet/blob/75c39f57507ed81f33571271b939de400a69adf0/src/demo.c#L156-L157
2. Started infinity loop: https://github.com/AlexeyAB/darknet/blob/75c39f57507ed81f33571271b939de400a69adf0/src/demo.c#L189
    * For each iteration started 2 additional threads: Yolo-detector and OpenCV video capture: https://github.com/AlexeyAB/darknet/blob/75c39f57507ed81f33571271b939de400a69adf0/src/demo.c#L192-L193 Total 3 threads:
        * fetch_thread - that captures frames from video file using OpenCV
        * detect_thread - that detects objects on the frame using Yolo
        * current - that show video frames with bounded boxes of detected objects
    * This loop works while OpenCV can capture frames from video file in the function `void *fetch_in_thread(void *ptr)`: https://github.com/AlexeyAB/darknet/blob/75c39f57507ed81f33571271b939de400a69adf0/src/demo.c#L61-L62
    * at the end of loop, we are waiting for the completion of these threads: https://github.com/AlexeyAB/darknet/blob/75c39f57507ed81f33571271b939de400a69adf0/src/demo.c#L211-L212
    * At each iteration of the cycle, the frame moves along such a pipeline: captured-frame -> frame-for-detection -> frame-for-show: https://github.com/AlexeyAB/darknet/blob/75c39f57507ed81f33571271b939de400a69adf0/src/demo.c#L216-L221

**Comment by johnnydept** [comment]
@AlexeyAB  Thanks Alex !

**Comment by kmsravindra** [comment]
@AlexeyAB , I am trying to understand demo.c indepth so that it will help to make some customizations to this code for our usecase which is at real time detection on HD stream...So, could you please help understanding the following - 

1. Some ball park numbers for the latency calculation in ms at each step in pipeline: captured frame --> frame-for-detection --> frame-for-show that you have seen / know of. 
2. what does free_image function do? Is it like freeing up the image from memory?
3. There is an if condition comparing l.type as REGION and DETECTION. Could you please clarify when do we use these 2 types (or do both get used?) and explain them a bit in this darknet dectection context?
4. I understood that there is some sort of frame buffer (FRAMES) and smoothening happening to pick the middle frame and draw bounding box on that middle frame which happens to be a mean of all the three frames. Does the default value of FRAMES =3 matter when the camera moves very fast? Can we set FRAMES = 1 to minimize the latency ? OR will FRAMES =1 draw inaccurate bounding boxes when camera moves fast ? 
5. What could be the typical latency when capturing a HD video to process through the entire pipeline of http_stream_capture --> processing by darknet --> rendering on to monitor. If we are able to get a 30FPS output using darknet, then which step could cause the bottleneck in terms of latency in your opinion?
6. What is frame_skip and delay part of the code do? There is some code that sets the value of frame_skip and accordingly compares delay...Are this frame_skip and delay caused due to darknet detection thread keeping up with the capture_stream FPS OR Is it caused due to frame_to_show thread keeping up with detection_thread? 
a. Could you please explain this at a high level?
               if(frame_skip == 0) frame_skip = 60;
                    else if(frame_skip == 4) frame_skip = 0;
                    else if(frame_skip == 60) frame_skip = 4;   
                    else frame_skip = 0;
b. Could you explain this at a high level as to how the fps is getting calculated?
if(delay < 0){
            delay = frame_skip;

            double after = get_wall_time();
            float curr = 1./(after - before);
            fps = curr;
            before = after;
        }

7. Could you please suggest on how can I get the frame number being captured, frame number being detected upon and the frame number being rendered on the monitor? This will help us to estimate the latency and do the performance profiling of our machine.
8.In fetch_in_thread, there seems to be an if condition to see if the option is a letter_box or not...could you tell me how I can pass this parameter? Will that have an impact on accuracy?
 void *fetch_in_thread(void *ptr)
{
    //in = get_image_from_stream(cap);
    int dont_close_stream = 0;    // set 1 if your IP-camera periodically turns off and turns on video-stream
    if(letter_box)
        in_s = get_image_from_stream_letterbox(cap, net.w, net.h, net.c, &in_img, cpp_video_capture, dont_close_stream);
    else
        in_s = get_image_from_stream_resize(cap, net.w, net.h, net.c, &in_img, cpp_video_capture, dont_close_stream);
    if(!in_s.data){
        //error("Stream closed.");
        printf("Stream closed.\n");
        flag_exit = 1;
        return EXIT_FAILURE;
    }
    //in_s = resize_image(in, net.w, net.h);

    return 0;
}

9. What does free_detections function do?

Thanks a lot!

**Comment by kmsravindra** [comment]
@AlexeyAB , Understood my above question was too lengthy to go through...Could you please atleast throw some light on the following in demo.c code, that would be very helpful - 

1. Can we set FRAMES = 1 to minimize the latency ? OR will FRAMES =1 draw inaccurate bounding boxes when camera moves fast ?

2. What is frame_skip and delay part of the code do? There is some code that sets the value of frame_skip and accordingly compares delay...Are this frame_skip and delay caused due to darknet detection thread keeping up with the capture_stream FPS OR Is it caused due to frame_to_show thread keeping up with detection_thread?
a. Could you please explain this at a high level?
if(frame_skip == 0) frame_skip = 60;
else if(frame_skip == 4) frame_skip = 0;
else if(frame_skip == 60) frame_skip = 4;
else frame_skip = 0;
b. Could you explain this at a high level as to how the fps is getting calculated?
if(delay < 0){
delay = frame_skip;

     double after = get_wall_time();
     float curr = 1./(after - before);
     fps = curr;
     before = after;
 }
3. Could you please suggest on how can I get the frame number being captured, frame number being detected upon and the frame number being rendered on the monitor? 

4. From the code I could make out that "in_s" is a resized image from "in_img" And "show_img" is getting set to "det_img". But no where in the code I could figure out how the "det_s" is getting resized back to the original image size to render the processed image at original dimensions? Could you please let me know?

5. The non-max-supression "nms" parameter defaults to 0.45 in demo.c and detector.c...Can this higher value be the cause of lot of false negatives, with zero objectiveness score, in my case? (I reported sometime back in here - #1739)
