### ISSUE TITLE
how to develop? workflow and debug

### ISSUE THREAD

**Issue by lzane** [AlexeyAB/darknet#311]
I currently clone this project and want to do some modification. I usually code with Python and has been a long time since I last code in C. But I can still read the code.

I train tiny-yolo in my python code and only get 8 FPS, that's not enough for my application. Then I try this project and see it can reach up to 20 FPS in demo mode. 

So I want to do more development on this project. But I don't know how to start. I have the following questions:

1. How's the training process, do I have to change the code, and then run `make clean` and `make` to see the result. Is there anything like jupyter notebook in Python where I can try my idea and keep the model and variables in memory. (about the workflow)

2. How do you debug your code? I installed Clion on my mac and cannot run in debug mode. Any idea about how to debug?

Thank you very much.

**Comment by AlexeyAB** [comment]
* You shouldn't change source code to train your model. Just follow this manual: https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects
* How to make wrapers for Python and use Darknet from Python you can see in the original repo: https://github.com/pjreddie/darknet/tree/master/python
* I debug source code using MSVS2015 on Windows, because Visual Studio has good built-in features for this.
* I use Darknet Yolo as DLL in a such way: https://github.com/AlexeyAB/darknet#how-to-use-yolo-as-dll
There are wrappers from C to C++ `yolo_v2_class.cpp` & `yolo_v2_class.hpp`. And my high performance code on C++: https://github.com/AlexeyAB/darknet/blob/master/src/yolo_console_dll.cpp
So you can achive even more FPS if you will use Darknet Yolo as SO-library, make with `LIBSO=1`: https://github.com/AlexeyAB/darknet#how-to-compile-on-linux

**Comment by lzane** [comment]
What about if I want to do some data augmentation? I have a function call `preprocess` and do some random transformation, scale and add noisy. So I want to add some code inside the repo. I know I can do them separately but that’s may ruin the suffering step.


----------------
Zane Lee 李泽帆

website: https://www.lzane.com
github: https://www.github.com/lzane

**Comment by AlexeyAB** [comment]
Data augmentation occurs in this function: https://github.com/AlexeyAB/darknet/blob/75c39f57507ed81f33571271b939de400a69adf0/src/data.c#L664
But I don't know simple way how to integrate your Python code to it.

**Comment by lzane** [comment]
Thanks for your patience.

I don’t mean I want to integrate my python code to this repo. I want to code them in C++. So I want to know how you develop this code.

And how can I add breakpoint and run the code in debug mode?


----------------
Zane Lee 李泽帆

website: https://www.lzane.com
github: https://www.github.com/lzane

**Comment by AlexeyAB** [comment]
All my code is cross-platform, so I just open `build\darknet\darknet.sln` in the Microsoft Visual Studio 2015 as described here: https://github.com/AlexeyAB/darknet#how-to-compile-on-windows

Then just click on a left side to set breakpoint and press run - execution will be stopped at this point:
![image](https://user-images.githubusercontent.com/4096485/34048021-37c3402c-e1c3-11e7-8aa4-8e6a4b200471.png)

Also you can try to Debug on Linux using GCC+GDB on Nsight Eclipse or Qt.

**Comment by lzane** [comment]
Ok, Thank you very much, I understand. Maybe it just cannot be developed on Mac
