### ISSUE TITLE
VOC data structure and learning

### ISSUE THREAD

**Issue by minjuprinces1004** [AlexeyAB/darknet#318]
hi, i'm still beginner of deep learning.
at learning using voc data:
   000001.jpg + 000001.xml => labels\000001.txt
the xml file have the object's coordinate, pose, truncated and difficult.
but, label file(000001.txt) has only coordinate and size.
where are the pose, truncated and difficult information used?

thank you.

**Comment by AlexeyAB** [comment]
Hi, as you can see in the PASCAL VOC Challenge - Detection Results: VOC2012 BETA - Competition "comp4" (train on own data) **aren't required** any information about `part, truncated, difficult, pose`: http://host.robots.ox.ac.uk:8080/leaderboard/displaylb.php?challengeid=11&compid=4

So it isn't in the label file(000001.txt). Because there are required only class-id and coordinates.

----

For example, `part` of objects required in this competition - Person Layout Results: VOC2010 BETA
Competition "comp7" (train on VOC2010 data): http://host.robots.ox.ac.uk:8080/leaderboard/displaylb_noeq.php?challengeid=6&compid=7

**Comment by minjuprinces1004** [comment]
thank you for your answer.
