### ISSUE TITLE
4K training dataset -> 1080p detection. Worth it?

### ISSUE THREAD

**Issue by WadRex** [AlexeyAB/darknet#3359]
Will I benefit from 4K images in Training/Validation dataset if I will be using 1080p images for detection? There is no problem in getting 4K images, so the quantity won't be the problem. I can do as much 4K pictures as 1080p. The reason why I want to use 4K images is that my objects can get VERY small (~around 15x15 pixels on 1080p), but they also can get big (almost whole screen).
So what model will be the best for me? It should be fast, but also accurate. I thought about Yolo V3 spp, but maybe there is better models.
Thanks in advance!

**Comment by AlexeyAB** [comment]
> Will I benefit from 4K images in Training/Validation dataset if I will be using 1080p images for detection? 

No.

If you want to use different frameworks (Tensorflow, Pytorch, OpenCV-dnn...) for detection, then use yolov3-spp.cfg.

Otherwise if you will use only this repository, then you can try to use new models: https://github.com/AlexeyAB/darknet/issues/3114#issuecomment-494148968

* https://github.com/AlexeyAB/darknet/files/3253820/yolo_v3_spp_pan_scale.cfg.txt

* or https://github.com/AlexeyAB/darknet/files/3267007/yolo_v3_tiny_pan_mixup.cfg.txt

You should train with `width=608 height=608` or `width=832 height=832` in your cfg-file

**Comment by WadRex** [comment]
Thanks, will try those ASAP!
