### ISSUE TITLE
Region layer 

### ISSUE THREAD

**Issue by johnnydept** [AlexeyAB/darknet#338]
float *swap = calloc(layer_size*layers*batch, sizeof(float));
		int i, c, b;
		// assume batch =1; layers = 13x13 = 169; layer_size = 5 archor num( 4 coord + 1 prob) =25;         
		for (b = 0; b < batch; ++b) {
			// channel index
			for (c = 0; c < layers; ++c) {
				// layer grid index
				for (i = 0; i < layer_size; ++i) {
					int i1 = b*layers*layer_size + c*layer_size + i;
					int i2 = b*layers*layer_size + i*layers + c;
					swap[i2] = x[i1];	
				}
			}
		}

Hi, @AlexeyAB , Can you briefly explain the swapping process in forward_region_layer?

**Comment by AlexeyAB** [comment]
@johnnydept Hi,

This is Premute-layer from Caffe: https://github.com/BVLC/caffe/commit/b68695db42aa79e874296071927536363fe1efbf
to change a blob with shape `N x C x H x W` to `N x H x W x C`
* N - number in the batch
* C - channel
* H - height
* W - width

About this code: https://github.com/AlexeyAB/yolo2_light/blob/86de0de76709e9a07d38555813bffefc87a6dc49/src/yolov2_forward_network.c#L284-L299

**Comment by johnnydept** [comment]
@AlexeyAB  Thank you so much. 👍

**Comment by johnnydept** [comment]
@AlexeyAB  Hi Alex, Sorry to bother you again, I notice original darknet doesnt use this premute-layer (flatten). Instead, it just goes with the 
             `for(n = 0; n < l.n; ++n) // for all 5 archors`
            `int index = entry_index(l, b, n*l.w*l.h, 0);`
            `activate_array(l.output + index, 2*l.w*l.h, LOGISTIC);`
            `index = entry_index(l, b, n*l.w*l.h, l.coords);`
            `if(!l.background) activate_array(l.output + index,   l.w*l.h, LOGISTIC);`
            `index = entry_index(l, b, n*l.w*l.h, l.coords + 1);`
Seem original darknet just activates t0 probs and coords?

**Comment by AlexeyAB** [comment]
@johnnydept Hi,

Seem original repo is a little bit optimized to do LOGISTIC **activation on a continuous arrays** using `activate_array()`:
* activate X and Y coords: `activate_array(l.output + index, 2*l.w*l.h, LOGISTIC);` instead of https://github.com/AlexeyAB/darknet/blob/a1af57d8d60b50e8188f36b7f74752c8cc124177/src/region_layer.c#L77-L78
* activate T0: `activate_array(l.output + index,   l.w*l.h, LOGISTIC);` instead of https://github.com/AlexeyAB/darknet/blob/a1af57d8d60b50e8188f36b7f74752c8cc124177/src/region_layer.c#L154-L157

And then original repo uses function `entry_index()` in the`get_region_boxes()`, to access to the coords, t0 and probabilities: https://github.com/pjreddie/darknet/blob/80d9bec20f0a44ab07616215c6eadb2d633492fe/src/region_layer.c#L405-L416
instead of access to plane array after flatten(): https://github.com/AlexeyAB/darknet/blob/a1af57d8d60b50e8188f36b7f74752c8cc124177/src/region_layer.c#L338-L348

**Comment by johnnydept** [comment]
@AlexeyAB  Thanks Alex. So i assume original repo works better if its optimised.

**Comment by AlexeyAB** [comment]
@johnnydept Yes, this part of region layer works little bit faster in the original repo.

**Comment by AlexeyAB** [comment]
@johnnydept It would be great if you measured performance on Linux using the same model on my repository and original.

**Comment by johnnydept** [comment]
@AlexeyAB  Alright, i will let you know :)
