### ISSUE TITLE
Detection result of image and video frame are different.

### ISSUE THREAD

**Issue by xiasun** [AlexeyAB/darknet#341]
Hi there, thank you for reading this.

I am using **yolo_console_dll.cpp** without any modification to test one of my video. But the detection result of an video is different from a static image. Below are a example.
I wonder whether I have ignored any parameters or steps.

![nobox](https://user-images.githubusercontent.com/9067922/35047221-3bce9ee8-fbd4-11e7-9f7e-51beaaa40821.jpg)
![withbox](https://user-images.githubusercontent.com/9067922/35047222-3d43ea58-fbd4-11e7-9718-0bf484f38bc6.jpg)
![withbox2](https://user-images.githubusercontent.com/9067922/35047223-3ec834a6-fbd4-11e7-9377-d483583c1ee5.jpg)

To my current understanding, the difference is caused by the following sentences:
For video the yolo_console_dll.cpp is using:
`auto result = detector.detect_resized(*current_image, frame_size, 0.24, true);`
For image the yolo_console_dll.cpp is using:
`std::vector<bbox_t> result_vec = detector.detect(mat_img);`

But I have no further process then.
Thanks for your time!

**Comment by AlexeyAB** [comment]
@xiasun Hi,

Try to un-comment these lines and recompile: https://github.com/AlexeyAB/darknet/blob/5a2a5679708c098a9d9d5973bc485f2e3c35c61d/src/yolo_console_dll.cpp#L239-L243

**Comment by xiasun** [comment]
Hi @AlexeyAB  my original code has the above code un-commented, I tried to comment them and the difference between video and image is even larger...

**Comment by AlexeyAB** [comment]
@xiasun 

This is because asynchronous detection is implemented - for the most effective detection on the video stream from the video camera in real-time. Therefore, while the object is detected, one or several frames already have time to change, and the object shifts slightly. But you can solve it:

----

There are two ways to solve it:

1. **Using tracking - if you use OpenCV 3.x:**
* Un-comment this line: https://github.com/AlexeyAB/darknet/blob/5a2a5679708c098a9d9d5973bc485f2e3c35c61d/src/yolo_console_dll.cpp#L17
* Comment these lines: https://github.com/AlexeyAB/darknet/blob/5a2a5679708c098a9d9d5973bc485f2e3c35c61d/src/yolo_console_dll.cpp#L239-L243

----

2. **Or use synchronous detection instead of asynchronous:**
* Replace all these lines to this one: `std::vector<bbox_t> result_vec = detector.detect(cur_frame);`
https://github.com/AlexeyAB/darknet/blob/5a2a5679708c098a9d9d5973bc485f2e3c35c61d/src/yolo_console_dll.cpp#L165-L208
* Comment these lines: https://github.com/AlexeyAB/darknet/blob/5a2a5679708c098a9d9d5973bc485f2e3c35c61d/src/yolo_console_dll.cpp#L239-L243

**Comment by xiasun** [comment]
Thank you @AlexeyAB , the second solution worked for me well! Thanks for your great work!
At first I did take some time to read this consuming workflow but I didn't fully understand it. Your advice is of great help for my understanding! Thank you again!
