### ISSUE TITLE
Merge darknet-mobilenet-v2

### ISSUE THREAD

**Issue by deimsdeutsch** [AlexeyAB/darknet#3453]
https://github.com/WePCf/darknet-mobilenet-v2

**Comment by AlexeyAB** [comment]
@deimsdeutsch 

There is already grouped-convolutional and it supports MobileNet v2: https://github.com/AlexeyAB/darknet/issues/1730

You can train this cfg file https://github.com/AlexeyAB/darknet/files/3310574/mobilenet_v2.cfg.txt by using the latest version of my repository https://github.com/AlexeyAB/darknet

You just can't use trained weights-file from https://github.com/WePCf/darknet-mobilenet-v2 because there are some changes in the source code

----

https://github.com/WePCf/darknet-mobilenet-v2 can't be merged, because there are several changes which brake all other models:

* https://github.com/WePCf/darknet-mobilenet-v2/blob/5f53d475557e1dca1dd20150ace9f888e8712b99/src/image.c#L561-L585

* https://github.com/WePCf/darknet-mobilenet-v2/blob/5f53d475557e1dca1dd20150ace9f888e8712b99/src/image.c#L1434-L1467

* https://github.com/WePCf/darknet-mobilenet-v2/blob/5f53d475557e1dca1dd20150ace9f888e8712b99/examples/classifier.c#L580-L583

**Comment by deimsdeutsch** [comment]
@AlexeyAB 
So this is only for classification and not for object detection ?

**Comment by AlexeyAB** [comment]
@deimsdeutsch Yes, MobileNetv2 is Classifier.

You can try to implement Detector that is based on MobileNetv2, by using

* FPN + yolo layers as it is done in https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov3.cfg

* or TridentNet as it is done in https://github.com/AlexeyAB/darknet/blob/master/cfg/resnet152_trident.cfg

**Comment by deimsdeutsch** [comment]
@AlexeyAB 
When did these changes happen ?

Can you please update me with the new object detection models ?
mAP and inference time ?

Looks like i have a lot to catch upon.

**Comment by AlexeyAB** [comment]
@deimsdeutsch He added bias values for input image.

There are still no good tests on big datasets like MS COCO / OpenImages...
And new models are in progress.

But you can look at the intermediate comparison results: https://github.com/AlexeyAB/darknet/issues/3114#issuecomment-494148968

**Comment by NickiBD** [comment]
@AlexeyAB Hi ,

I have integrated Mobilenet-v2 (backbone)+yolo heads and trying to train it. However, it is not converging (the loss is high and the .mAP is 0 for 3000 iterations .I was wondering whether you can help me with that .

Many thanks with all the help .

**Comment by AlexeyAB** [comment]
@NickiBD Can you show your cfg-file mobilenetv2+yolo_head?

**Comment by NickiBD** [comment]
Hi @AlexeyAB 
Thanks for the reply .Please find the .cfg 
[mobilnetyolo.cfg.txt](https://github.com/AlexeyAB/darknet/files/3352772/mobilnetyolo.cfg.txt)

**Comment by deimsdeutsch** [comment]
@AlexeyAB 
Any updates ?

**Comment by deimsdeutsch** [comment]
@AlexeyAB 
Can you share a mobilenetv2 cfg file that i can train on imagenet ?

**Comment by AlexeyAB** [comment]
@deimsdeutsch In the first my post: 
https://github.com/AlexeyAB/darknet/files/3310574/mobilenet_v2.cfg.txt - you can train classifier on imagenet

**Comment by deimsdeutsch** [comment]
Last question..
How many iterations i need to train for imagenet model ?

**Comment by AlexeyAB** [comment]
@deimsdeutsch At least 600000
