### ISSUE TITLE
Opencv 4.1: different pkg-config library name

### ISSUE THREAD

**Issue by pliablepixels** [AlexeyAB/darknet#3479]
OpenCV 4.1 (not sure of earlier versions) seems to use `opencv4` instead of `opencv` for `pkg-config` (assuming you used `-D OPENCV_GENERATE_PKGCONFIG=ON`) 

Thanks for your fork. It works wonderfully with OpenCV 4.1 and CUDA 10.1

**Comment by AlexeyAB** [comment]
@pliablepixels Hi, thanks!

Do you think we should use both `opencv` and `opencv4` for supporting both OpenCV 4.x and OpenCV3.x/2.x?

I.e. use 
```
LDFLAGS+= `pkg-config --libs opencv`
COMMON+= `pkg-config --cflags opencv`
LDFLAGS+= `pkg-config --libs opencv4`
COMMON+= `pkg-config --cflags opencv4`
```
instead of: https://github.com/AlexeyAB/darknet/blob/5ec35922d5215e11466a9bb1602f81d1746ccbe5/Makefile#L79-L80

**Comment by AlexeyAB** [comment]
@cenit Hi, what do you think about this?

**Comment by pliablepixels** [comment]
I agree, I actually did something like  OPENCVPKG=`pkg-config --libs opencv || pkg-config --libs opencv4`

**Comment by cenit** [comment]
The problem here is only for the makefile. Unfortunately I think it’s not as easy as you say, because if you have both installed then you risk a mess. Autotools usually come to the rescue here, but I’d say it is an overkill.
First of all, i’d revert your common and ldflag order, so to have opencv4 appear first on the build line wrt opencv. Second, includes and linked files might even be ok since the first should resolve everything, but what about defines? You’d have defines for both version active on the same command line. You should test it thoroughly in a specific corner case maybe before pushing it. I think having both is becoming a little bit too common

**Comment by SalahAdDin** [comment]
https://github.com/pjreddie/darknet/pull/1348 This is a try to add supporting **OpenCV 4**.

**Comment by cenit** [comment]
close thanks to #4896 fixing makefile also for OpenCV 4.1
