### ISSUE TITLE
Slower when activating (optical flow) tracking

### ISSUE THREAD

**Issue by iraadit** [AlexeyAB/darknet#352]
Hi,

I installed CUDA 9.1, cudnn 7 and OpenCV 3.4 and executing `./uselib` (slightly modified to get a webcam video)

With a Titan X (Pascal)
Getting 30 FPS capture and 45-47 FPS detection.
When activating `TRACK_OPTFLOW`, the execution time drops to 15 FPS detection.

With an embedded GTX 1060
Getting 30 FPS capture and 19-22 FPS detection.
When activating `TRACK_OPTFLOW`, the execution time drops to 8-9 FPS detection (20-30 FPS capture).

I thought that the Optical Flow would be far faster than that.

So, I've 3 questions on that.

1. If I understand well, the Optical Flow tracking is for now only used to track the objects from one frame to the next, still detecting on each of them?

2. So, if I wanted to use a technique similar to "Tracking by detection", I should detect on every x frames instead on each of them, while continuing to track on each of them?
https://github.com/samuelmurray/tracking-by-detection
http://www.cvlibs.net/software/trackbydet/

3. I saw that they are parameters of compilation for CUDA/nvcc  to set to activate concurrency, have you done it? (to have detection and tracking working at the same time on the graphic card)
https://devblogs.nvidia.com/gpu-pro-tip-cuda-7-streams-simplify-concurrency/

Thank you

**Comment by AlexeyAB** [comment]
@iraadit Hi,

Tracking using optical flow - is important when the frame capture is faster than detection, i.e. when Capture FPS > Detection FPS. It can be if your GPU is slow or if you use large neural model with high resolution. Because Tracking works about 40x times faster than Detection.

----

1. If you use `#define TRACK_OPTFLOW` and, for example, if you get 15 FPS detection and 45 FPS capture, then:
    * Tracking works with the same FPS as Capture = 45 FPS, i.e. **tracking is done for each frame**
    * Detection works with FPS = 15, i.e. **detection is done for each 3rd frame**

Also if some object with the same `track_id` was Detected more than once times, then it will be Tracked even if it isn't detected in the current Detection. But if object will not Detected 3 times, then tracking will be stoped: https://github.com/AlexeyAB/darknet/blob/e11430970b5470fb92127901454a1c90e5cc45e4/src/yolo_console_dll.cpp#L294-L304

2. Yes, as in point 1, for 15 FPS detection and 45 FPS capture and tracking - detection will be for every 3rd frame, while tracking will be for each frame.

3. Yes, I use CUDA-streams for parallel execution of several CUDA-functions on the same GPU:
    * https://github.com/AlexeyAB/darknet/blob/e11430970b5470fb92127901454a1c90e5cc45e4/src/yolo_v2_class.hpp#L183
    * https://github.com/AlexeyAB/darknet/blob/e11430970b5470fb92127901454a1c90e5cc45e4/src/cuda.c#L64-L74

But judging by the `nvvp` (nvidia profiler), I have not done it optimally, I will still optimize it.

----

So if you use mobile-GPU such as GeForce GTX 760M - you can get about 2 FPS Detection and 20 FPS Capture & Tracking even on tiny-model, but really, tracking will process 40 fps:

* 20 FPS - Tracking from the frame at which the Detection occurred to the current frame - **because while we did Detection, 20 frames had already passed**: https://github.com/AlexeyAB/darknet/blob/e11430970b5470fb92127901454a1c90e5cc45e4/src/yolo_console_dll.cpp#L276-L291

* 20 FPS - Tracking from the current frame to that frame on which we will get new detection - this tracking we see on the screen for each captured frame: https://github.com/AlexeyAB/darknet/blob/e11430970b5470fb92127901454a1c90e5cc45e4/src/yolo_console_dll.cpp#L341

**Comment by iraadit** [comment]
I'm finding this answer to my old question now, and I'm thanking you now as it seems I didn't send my answer months ago.

So, thanks again for the good explanations!
