### ISSUE TITLE
Different recall values for pjreddie/darknet and AlexeyAB/darknet

### ISSUE THREAD

**Issue by hy9be** [AlexeyAB/darknet#365]
Hi, I just observed the recall value I get from the two forks are different. And what is even more confusing for me, is that for the weights I got from 10000 and 20000 batches, AlexeyAB/darknet shows 20000 weights have better recall, while pjreddie/darknet shows 10000 weights have better recall. 

I tried to search in both repository issues but did not find an explanation for the difference. @AlexeyAB could you shed some lights here? Thanks!

In AlexeyAB/darknet
```
../../darknet_AlexeyAB/darknet detector recall cfg/easy.data cfg/easy-with-anchors.cfg backup/easy-with-anchors_10000.weights
IOU: 49.65%     Recall:52.37%
../../darknet_AlexeyAB/darknet detector recall cfg/easy.data cfg/easy-with-anchors.cfg backup/easy-with-anchors_20000.weights
IOU: 53.55%     Recall:62.61%
```
In pjreddie/darknet
```
../../darknet/darknet detector recall cfg/easy.data cfg/easy-with-anchors.cfg backup/easy-with-anchors_10000.weights
IOU: 49.10%     Recall:49.40%
../../darknet/darknet detector recall cfg/easy.data cfg/easy-with-anchors.cfg backup/easy-with-anchors_20000.weights
IOU: 46.66%     Recall:44.18%
```

**Comment by hy9be** [comment]
And the loss values during training are also different.

**Comment by AlexeyAB** [comment]
Hi, what repo did you use for training?

**Comment by hy9be** [comment]
Was about to add that lol. I used pjreddie/darknet. Does that matter?

**Comment by AlexeyAB** [comment]
1. There are some differents between this repo and original: https://github.com/AlexeyAB/darknet/issues/362#issuecomment-361918956

2. Also what cfg-file did you use as inital for your easy-with-anchors.cfg?

3. Also check that these 3 lines are the same in both your Darknets:
* this repo: https://github.com/AlexeyAB/darknet/blob/993e3a38aab390625a1ac2b425c75883bbc684fe/src/detector.c#L407-L409
* original repo: https://github.com/pjreddie/darknet/blob/80d9bec20f0a44ab07616215c6eadb2d633492fe/examples/detector.c#L511-L513

**Comment by hy9be** [comment]
1. I will take a look. I understand, appreciate and respect the further work you did in this fork. I benefit from them a lot. The thing is, now I cannot confidently choose the model with better recall between the 10000 batch and 20000 batch weights, given the result above..

2. It is modified from tiny-yolo.cfg

3. They are the same: 0.001, 0.5 and 0.4, respectively

**Comment by hy9be** [comment]
@AlexeyAB The difference of IOU and recalls for a yolo-v2 network is even more:

In AlexeyAB/darknet
```
../../darknet_AlexeyAB/darknet detector recall cfg/easy.data cfg/yolo-v2-fromScratch.cfg backup/yolo-v2-fromScratch_final.weights
IOU: 57.55%     Recall:66.61%
```
In pjreddie/darknet
```
../../darknet/darknet detector recall cfg/easy.data cfg/yolo-v2-fromScratch.cfg backup/yolo-v2-fromScratch_final.weights
IOU: 25.54%     Recall:20.80%
```

**Comment by AlexeyAB** [comment]
I think that problem is in these 2 lines, where is hardcoded usage of `data/coco_val_5k.list` instead of your validation-dataset, for `detector recall`: https://github.com/pjreddie/darknet/blob/80d9bec20f0a44ab07616215c6eadb2d633492fe/examples/detector.c#L497-L498

----

You should fix code in the original repo.

1. Try to change these lines in original repo: https://github.com/pjreddie/darknet/blob/80d9bec20f0a44ab07616215c6eadb2d633492fe/examples/detector.c#L497-L498

To these lines:
```cpp
	list *options = read_data_cfg(datacfg);
	char *valid_images = option_find_str(options, "valid", "data/train.txt");
    list *plist = get_paths(valid_images);
    char **paths = (char **)list_to_array(plist);
```

2. Change this 1 line: https://github.com/pjreddie/darknet/blob/80d9bec20f0a44ab07616215c6eadb2d633492fe/examples/detector.c#L490
To this `void validate_detector_recall(char *datacfg, char *cfgfile, char *weightfile)`

3. And change this line: https://github.com/pjreddie/darknet/blob/80d9bec20f0a44ab07616215c6eadb2d633492fe/examples/detector.c#L689
to this `    else if(0==strcmp(argv[2], "recall")) validate_detector_recall(datacfg, cfg, weights);`

----

As we can see, calculation of IoU and Recall are the same in both repo:
![image](https://user-images.githubusercontent.com/4096485/35731799-1eb8c0a8-0828-11e8-98b5-231cb4f82fbe.png)

Only changed:
* path to validation dataset
* and this line:
    * this repo: `get_region_boxes(l, 1, 1, thresh, probs, boxes, 1, 0);`
    * original repo: `get_region_boxes(l, sized.w, sized.h, net->w, net->h, thresh, probs, boxes, 0, 1, 0, .5, 1);`

![image](https://user-images.githubusercontent.com/4096485/35732096-41c1bdba-0829-11e8-945d-ebc9fca59bd6.png)

**Comment by hy9be** [comment]
@AlexeyAB Thanks for the investigation!

I actually already made changes to the path to val dataset to a hardcoded path, which points to my val.txt file.

So it looks the key different here is the ``get_region_boxes`` call. I looked into the ``region_layer.c`` file, and found major differences in the ``get_region_boxes`` function body. @pjreddie did some major code changes after this repo forked from his repo: https://github.com/pjreddie/darknet/blame/master/src/region_layer.c
