### ISSUE TITLE
small object detection 

### ISSUE THREAD

**Issue by OPPOA113** [AlexeyAB/darknet#39]
@AlexeyAB #19 
can we adding the 10th layer(52x52x256) to last conv layer for samll object detection just as 24th layer?
![cc](https://cloud.githubusercontent.com/assets/4974108/23829835/d558e002-0736-11e7-9cb5-0d716e2a30a8.jpg)

**Comment by AlexeyAB** [comment]
@OPPOA113 

What is the benefit?

If you want to detect small objects you can simple increase network resolution to `height=1088`, `width=1088` and `subdivision=64` in your `.cfg`-file:  https://github.com/AlexeyAB/darknet#how-to-improve-object-detection

But it requires at least **4 GB** GPU-RAM.

As a result:

* it will be possible on input image 1088x1088 to detect objects of size 16x16, which placed from each other at least at distance 32 pixels.

*  it will be possible on input image 544x544 to detect objects of size 8x8, which placed from each other at least at distance 16 pixels.

...

Total objects that can be found on 1 image are **1156** objects = (34x34)

![resolution](https://cloud.githubusercontent.com/assets/4096485/23911421/d2ba4350-08ed-11e7-93c6-e4732a3e03e5.jpg)

**Comment by iraadit** [comment]
Hi @AlexeyAB 
Could you please explain how you get the object sizes from the size of the network?

1088 / 32 = 34 boxes by side

But where the "16x16 pixels" comes from? And the "at least at distance 32 pixels"?

Thank you

**Comment by AlexeyAB** [comment]
@iraadit Hi,

These are very approximate estimates:

* 416 / 32 = 13 boxes 
* 1 side = 32x32 pixels
* Yolo uses `num=5` anchors, then it detect 5 objects for each side (for each box 32x32 pixels)
    * So **with the declared precision** (73.4 - 76.8 mAP) in PascalVOC competitions, **only 1 object can be detected in one side (box 32x32)**
    * 5 object can be detected with precision more less than declared

* Yolo v2 uses both 13x13 and 26x26 features maps
    * so Yolo can detect even if object detected on 26x26 feature map (but not detected on 13x13)
    * 416 / 26 = 16 pixels - size of object
    * Yolo **can detect smaller objects than 16 pixels - but this will greatly reduce the precision** of detection

Page 3: https://arxiv.org/pdf/1612.08242v1.pdf

> Fine-Grained Features.This **modified YOLO predicts detections on a 13 × 13 feature map**. While this is sufficient for large objects, **it may benefit from finer grained features for localizing smaller objects**. Faster R-CNN and SSD both run their proposal networks at various feature maps in the network to get a range of resolutions. We take a different approach, simply **adding a passthrough layer that brings features from an earlier layer at 26 × 26 resolution**

**Comment by iraadit** [comment]
Ok, I understood for the 16 pixels object, thank you for you clear explanation

So, if we still use the base network resolution (416), we will be able to detect 16x16 pixels object on a 416x416 image; using a 208x208 image as input, we would be able to detect 8x8 pixels object though, because this image would be resized to 416x416 at the start of the process

When increasing the network resolution to 1088, we would keep the same minimum size for detection (16x16pixels) for an input image of 1088, but would be able to detect a 8x8pixels object from a 544x544 image; the difference with the 416 network resolution would be the number of boxes (34 instead of 13) 

If we we're using an input 720x576 (PAL) image with a 1088 network resolution, considering the change in ratio, we would therefore be able to detect 10x8 pixels object (approx; exact values would be 10.59x8.47)? **Is that right**?

 
I don't understand when you say this :
> - So with the declared precision (73.4 - 76.8 mAP) in PascalVOC competitions, only 1 object can be detected in one side (box 32x32)
> - 5 object can be detected with precision more less than declared
> Yolo can detect smaller objects than 16 pixels - but this will greatly reduce the precision of detection

If I wanted to be able to detect more close objects (up to 5) or objects smaller than 16 pixels (say with input image 416 and network resolution 416), at the expense of some precision, what should I change in the configuration file?
In my use case, precision of localization wouldn't be the principal need (it would be possible to zoom to detect the localization more precisely), but detecting smaller objects (while still being able to detect "normal sized" (similar to VOC) objects) would be a must

Thank you a lot

**Comment by AlexeyAB** [comment]
@iraadit 

> If I wanted to be able to detect more close objects (up to 5) or objects smaller than 16 pixels (say with input image 416 and network resolution 416), at the expense of some precision, what should I change in the configuration file?

You should:

* or at 4x times increase network resolution: from 416x416 to 1664x1664
* or divide your image into 16 images: 160x144 - and process it separately

In this case may be more preferable to use Tiny-Yolo with high resoulution network 1664x1664 instead of Full-Yolo with low resolution network 832x832. For small objects Tiny-Yolo 1664x1664 may provide higher ratio `accuracy/time` than Full-Yolo 832x832.


You should simply increase `height`,  `width` in your `.cfg`-file and set `subdivisions=64`: https://github.com/AlexeyAB/darknet#how-to-improve-object-detection

**Comment by guangwei** [comment]
I use yolov3-tiny.cfg, either change layers = -1, 11 or stride=4,   training will exit with no information.

**Comment by guangwei** [comment]
@AlexeyAB 
I use yolov3-tiny.cfg, either change layers = -1, 11 or stride=4, training will exit with no information.

**Comment by AlexeyAB** [comment]
@guangwei 

Just use https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov3-tiny_3l.cfg without changing layers and stride.
