### ISSUE TITLE
traing problem:can't load image in linux

### ISSUE THREAD

**Issue by OPPOA113** [AlexeyAB/darknet#42]
@AlexeyAB    
Hello
    27 route  26 24
   28 conv   1024  3 x 3 / 1    13 x  13 x3072   ->    13 x  13 x1024
   29 conv     30  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x  30
   30 detection
Loading weights from darknet19_448.conv.23...Done!
/home/mars/yolo/darknet/data/voc-person/000050.jpg
/home/mars/yolo/darknet/data/voc-person/000089.jpg
/home/mars/yolo/darknet/data/voc-person/000030.jpg
/home/mars/yolo/darknet/data/voc-person/000041.jpg
/home/mars/yolo/darknet/data/voc-person/000104.jpg
/home/mars/yolo/darknet/data/voc-person/000035.jpg
/home/mars/yolo/darknet/data/voc-person/000073.jpg
/home/mars/yolo/darknet/data/voc-person/000017.jpg
Couldn't open file: /home/mars/yolo/darknet/data/voc-person/000050.txt
Couldn't open file: /home/mars/yolo/darknet/data/voc-person/000104.txt
段错误 (核心已转储)
mars@harzone:~/yolo/darknet$ ./darknet imtest /home/mars/yolo/darknet/data/voc-person/000050.jpg
/home/mars/yolo/darknet/data/voc-person/000050.jpg
L2 Norm: 347.581116

Linux 
when i train my new class ,why it cannot load images? but i can imtest it????
thanks.

**Comment by AlexeyAB** [comment]
@OPPOA113 

Your porblem is that you haven't `000050.txt` file in the `/home/mars/yolo/darknet/data/voc-person/000050.txt`

You can do imtest because imtest doesn't require `000050.txt`-file, its only requires `000050.jpg`


Check your dataset by using latest version of tool on Linux: https://github.com/AlexeyAB/Yolo_mark
Go through all the images by pressing the **SPACE button**.

**Comment by OPPOA113** [comment]
it work now ,thank you
