### ISSUE TITLE
CUDA memory allocation failed while training for high resolution images

### ISSUE THREAD

**Issue by spaul13** [AlexeyAB/darknet#4270]
when I am trying to train the model for high resolution images on GPU, I am getting the error of "_**CUDA memory allocation failed**_"

For me batch size = 64, subdivisions =8 and I want to train with 50 1K (1024*1024) images, still I am getting the error.

Can anyone plz tell me how to get rid of this error? Is there any trick to get rid of this problem?

**Comment by AlexeyAB** [comment]
* set `batch=64 subdivisions=64`
* show screenshot of the error

**Comment by LukeAI** [comment]
you can do a few things.
- train at a lower resolution - seriously, training at 1024*1024 is going to be soooo slow and won't give you better results than 608 * 608 (unless you have a really unusual special case)- your results will most likely be worse because you will have to use smaller mini-batches (larger subdivisions). Train at 608 * 608, if you really want to you can always finetune at 1024*1024 but in my experience it doesn't improve things except for really tiny objects.
- increase subdivisions to 16 - or 32 or 64 if it still happens.
- set all the random=1 to random=0
- don't compile with cudnn_half=1

**Comment by spaul13** [comment]
Thanks a lot @AlexeyAB @LukeAI increasing the subdivisions, really helps :)
