### ISSUE TITLE
LSTM frame sequence length

### ISSUE THREAD

**Issue by apennisi** [AlexeyAB/darknet#4291]
Hi @AlexeyAB ,

I am trying to use the yolo_v3_tiny_pan_lstm.cfg file with my dataset. My dataset is made of multiple video sequences with variable sequence length. 
If I cut the length of the sequences in order to be the same for all the videos, where do I have to specify the sequence length in the cfg file?

Can you tell me what the following parameters mean?

`track=1`
`time_steps=3	# for 8GB GPU`
`augment_speed=3`
`sequential_subdivisions=4`

Thanks a lot for your work!

**Comment by AlexeyAB** [comment]
track=1 - will be used random sequences of images from train.txt instead of random images
time_step=3 - the length of sequence in one mini_batch (3 images)
augment_speed=3 - (interleaving) images will be randomly taken from train.txt with indexes (5,6,7) or (9,12,15) ...
sequential_subdivisions=4 - the length of sequence in one batch (time_step X sequential_subdivisions)

More: https://github.com/AlexeyAB/darknet/wiki/CFG-Parameters-in-the-%5Bnet%5D-section

**Comment by apennisi** [comment]
Thanks! :) So, if I have sequences of 100 frames, do I have to set for example time_step=5 and sequential_subdivisions=20?

**Comment by AlexeyAB** [comment]
> if I have sequences of 100 frames, do I have to set for example time_step=5 and sequential_subdivisions=20?

Yes.

Also you should set time_step= as much as possible (not more than sequence size), but your GPU VRAM size is limited.

Also `mini_batch=batch/subdivisions` should be more than 1 to get good accuracy - the more - the better.

So you have to find a compromise set higher time_step= or set lower subdivisions=

**Comment by apennisi** [comment]
Perfect! Thanks for your help!
