### ISSUE TITLE
Question about the Scale in C code

### ISSUE THREAD

**Issue by androuino** [AlexeyAB/darknet#4424]
Hi, everyone. I just have a simple question about the Scale that I found in the code for training Object Detection but I don't know much what is it for or how it affect the accuracy or training the weights? As of the current version of C code, it was hard coded as 1.4, what does this means? Also does this Scale applies also with Image Classification? Thank you.

**Comment by AlexeyAB** [comment]
https://arxiv.org/pdf/1612.08242.pdf

![image](https://user-images.githubusercontent.com/4096485/69950983-7169cb80-1505-11ea-8884-a82c0ddc4994.png)


Multi-Scale Training. The original YOLO uses an input
resolution of 448 × 448. With the addition of anchor boxes
we changed the resolution to 416×416. However, since our
model only uses convolutional and pooling layers it can be
resized on the fly. We want YOLOv2 to be robust to running
on images of different sizes so we train this into the model.
Instead of fixing the input image size we change the network every few iterations. Every 10 batches our network
randomly chooses a new image dimension size. Since our
model downsamples by a factor of 32, we pull from the
following multiples of 32: {320, 352, ..., 608}. Thus the
smallest option is 320 × 320 and the largest is 608 × 608.
We resize the network to that dimension and continue training.
...

**Comment by androuino** [comment]
Thanks for the quick response @AlexeyAB. Thanks for the info, as of now, I've to train a model without having it to apply the scale since the detection that I wanted it to apply is quite stationary so I think I don't to apply the scale, so what I did is just put a value of _0_ to it. My observation from changing the scale's value is that the training goes a little bit faster and the detection dramatically improved. 

One more question though is that this **Scale** also applies to Image _Classification_?
Thanks.

**Comment by AlexeyAB** [comment]
Classifier doesn't use random= parameter and doesn't randomly resize the network during training.

**Comment by androuino** [comment]
Thanks. Closing this question now.
