### ISSUE TITLE
re-sample data

### ISSUE THREAD

**Issue by jackchen0117** [AlexeyAB/darknet#443]
Hi AlexeyAB,

Would you please tell me what do I suppose to do if I would like to re-sample data?
Put the same picture path multiple times in train.txt ?
Say, if I would like to re-sample 004.jpg:

in train.txt:
folder/001.jpg
folder/002.jpg
folder/003.jpg
folder/004.jpg
folder/004.jpg
folder/004.jpg
folder/005.jpg

Is it possible to re-sample bounding box? (Dose this make sense if data are imbalanced?)
 Say, if I would like to re-sample the box of class number 0 in 001.jpg:

in 001.txt:
0,2,2,2,2
0,2,2,2,2
3,5,6,7,8
4,9,6,3,6

Is this correct?
Thank you!

**Comment by AlexeyAB** [comment]
@jackchen0117 Hi,
Do you want to use multiple times one image and one objec for training?

* Yes, you can just write multiple times `folder/004.jpg` but if you then will use Yolo_mark, it can remove duplicates. So I offten just copy `004.jpg` and `004.txt` to several file `004_1.jpg`, `004_1.txt`, `004_2.jpg`, `004_2.txt`, ... and put its paths to the `train.txt`

* About use multiple identical labels of the one object, I have not thought about all the side effects, but I think this is a bad idea. Because only one of box will have the best IoU (intersct of union): https://github.com/AlexeyAB/darknet/blob/880cf187d87c904f5fe574802ecff99118643f2d/src/region_layer.c#L253
So all other boxes will not be used.
Also during calculating mAP, it will gives you false-negatives (many truth-boxes for one detected-object).

**Comment by jackwei0117** [comment]
AlexeyAB ,

Thank you very much for your enthusiasm of helping people, I've learned a lot from you. :)
