### ISSUE TITLE
how to free the network pointer?

### ISSUE THREAD

**Issue by stephanecharette** [AlexeyAB/darknet#4603]
Using the libdarknet.so API from darknet.h.  The call I'm using to create a network is this one:

`LIB_API network *load_network_custom(char *cfg, char *weights, int clear, int batch);`

But when I'm done with it, how to free it?  There doesn't seem to be any sort of `free_network()` API exposed.

**Comment by stephanecharette** [comment]
In case other people end up here in the future, it looks like the answer might very well be a function called `free_network()` defined in network.h, but not exposed in darknet.h.

Then remember to also call `free(net)` since both `load_network()` and `load_network_custom()` use `calloc()` to allocate the network structure.

**Comment by AlexeyAB** [comment]
I added `free_network()` to the darknet.h https://github.com/AlexeyAB/darknet/commit/489ea7fdce771144c3ef39d870926c71a1587af5

**Comment by jerry73204** [comment]
In the current design as shown [here](https://github.com/AlexeyAB/darknet/blob/08bc0c9373158da6c42f11b1359ca2c017cef1b5/include/darknet.h#L930-L934), `load_network()` returns a `network*` pointer that is internally allocated by `calloc()`. However, `free_network(network net)` takes a copy of a struct instead of a pointer. Users have to explicitly `free()` the `network*` pointer in order not to leak the memory.

IMO, it is an error-prone design because it's easy to forget to call `free()`, leading to memory leak. The `calloc()` beneath the `load_network()` is an internal knowledge that is neither documented nor exposed to user. It would be better `free_network()` takes an `calloc`ed pointer instead.
