### ISSUE TITLE
ZED camera with Jetson TX2 - got 10 fps

### ISSUE THREAD

**Issue by alwan14** [AlexeyAB/darknet#4688]
Hi @AlexeyAB, I want ask you.
I use the darknet program on your repository on Jetson TX2 with ZED camera, I just got 10 fps. I use yolov3-tiny.cfg
is it possible for me to get 20 fps using yolov3-tiny.cfg ?
i`m using the latest version of Darknet.

**Comment by AlexeyAB** [comment]
Yolov3-tiny can be processed with 16 FPS (62ms) on Jetson TX2. 
But if ZED-camera is also processed on Jetson TX2, then it will be about ~10 FPS.


* You can try to use https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov3-tiny-prn.cfg instead of yolov3-tiny.

* And use the fastest mode on ZED-camera - use `DEPTH_MODE_PERFORMANCE` instead of `DEPTH_MODE_ULTRA` and recompile https://github.com/AlexeyAB/darknet/blob/14172d42b68cf9c81ca1150020475f3e79c82fab/src/yolo_console_dll.cpp#L337

* if it doesn't help much, then set `width=320 height=320` in cfg-file

**Comment by alwan14** [comment]
oke thank @AlexeyAB I can get 17 fps using zed stereo.
if I use zed mini, will the result be the same as the usual zed ?

**Comment by AlexeyAB** [comment]
> if I use zed mini, will the result be the same as the usual zed ?

Yes. FPS will be the same. Depth error will be higher.

Follow this suggestions to improve FPS: https://github.com/AlexeyAB/darknet/issues/4688#issuecomment-574120154

**Comment by alwan14** [comment]
okay thank you @AlexeyAB

**Comment by alwan14** [comment]
Hi @AlexeyAB, I want ask you.
Can I directly use ZED mini on the darknet program in your repository? or something needs to be set up again ?

**Comment by AlexeyAB** [comment]
> directly 

What do you mean?


https://github.com/AlexeyAB/darknet#how-to-compile-on-linux-using-make

`ZED_CAMERA=1` to build a library with ZED-3D-camera support (should be ZED SDK installed), then run 

`LD_LIBRARY_PATH=./:$LD_LIBRARY_PATH ./uselib data/coco.names cfg/yolov3.cfg yolov3.weights zed_camera`

**Comment by alwan14** [comment]
if i use zed mini to measure the distance with your program, is there anything that needs to be set ?
I want to use a ZED mini camera, not an usual ZED

**Comment by AlexeyAB** [comment]
Everything the same

**Comment by alwan14** [comment]
okay thank you @AlexeyAB

**Comment by husseinpasha** [comment]
Hi,
I am using the ZED camera with a Jetson TX2. I run this code in the terminal and it works well: 
~/darknet_test$ LD_LIBRARY_PATH=./:$LD_LIBRARY_PATH ./uselib data/coco.names cfg/yolov4.cfg yolov4.weights zed_camera
I am trying to send the XYZ coordinates that are written on top of the detected objects to my stepper motors. The problem is I couldn't find the file that is being executed and prints those numbers on the screen. I manipulated the darknet/src/yolo_console_dll.cpp file but nothing changed. Then I deleted all files from the darknet directory except yolov4.weights, uselib, libdarknet.so,  coco.names, and yolov4.cfg. The program still works! I don't know where is that file/s is being executed. If I can find that file then I can export the XYZ coordinates. 
Would you please help me with this?
