### ISSUE TITLE
about averages yolo deltas

### ISSUE THREAD

**Issue by chengweige** [AlexeyAB/darknet#4885]
@AlexeyAB 
in the yolo_layer, you did average the delta for x、 y、 w and h due to odelta_yolo_box() accumulation，so why confidence and class delta didn't？

**Comment by AlexeyAB** [comment]
Just to avoid very high deltas
because deltas `w,h,` **add up** and can be very large, even higher than 10, and very high delta can make training unstable, while deltas for `classes` don't add up and always = [-1; 1]


https://github.com/AlexeyAB/darknet/blob/653eceb1a72641cf978734dc15257f8273f1ac94/src/yolo_layer.c#L237-L252

**Comment by chengweige** [comment]
i see, thank you
