### ISSUE TITLE
Convert model to Keras

### ISSUE THREAD

**Issue by scm-ns** [AlexeyAB/darknet#489]
Hey Alexey, 
     This fork is great. Makes it extremely easy to train my own yolo models. So thank you. 

I was wondering how I could go about converting the model created by your version of darknet into the keras format. 

https://github.com/allanzelener/YAD2K
^ Works with pjreddie's version. Do you think it will work with the models that your version creates ? I was able to use it to get a keras model. Am I missing something ? 

Are there any major difference between how you store the model vs how pjreddie stores the model ? 

Thank you

**Comment by AlexeyAB** [comment]
Hi, There are no fundamental changes, so everything should work.

There is only one fix - in reorg-layer, that slightly increases precision: https://github.com/AlexeyAB/darknet/commit/fe44d3d0f29e96714de75234e1fd7e40b05b0296#diff-e06ddf0ed11f062038cea235e04bab04R102
so to get the same result you should train with `[reorg_old]` layer instead of `[reorg]` layer in your cfg-file, just change this line `[reorg]` to the `[reorg_old]` and train your model: https://github.com/AlexeyAB/darknet/blob/3e5abe0680c6112c9674204c22db7bd4b238d2b5/cfg/yolo-voc.2.0.cfg#L206

But if you use tiny-yolo or yolo9000 there isn't any changes.

**Comment by scm-ns** [comment]
I just tested it out using the weights your fork creates, and YAD2K scripts work and the resulting model can detect objects. 

Thank you Alexey !
