### ISSUE TITLE
How to Input data with channels>3

### ISSUE THREAD

**Issue by ahsan856jalal** [AlexeyAB/darknet#493]
@AlexeyAB 
I just wonder , if I have frames from GMM and optical flow, can I concatenate with RGB image and make it 5 channel data and pass it to darknet , by just changing ch=3 -> ch=5 and slight change in the first convolutional layer in the .cfg file

**Comment by AlexeyAB** [comment]
You should change source code in many places to do it:

* in `load_data_detection()` change image loading (for loading GMM+RGB) and data augumentation for processing 5 channels: https://github.com/AlexeyAB/darknet/blob/101de2b07aa2feefa74f7e73876fd5cc8fc696cf/src/data.c#L671-L721

* in `test_detector()` change image loading, for loading GMM+RGB instead of RGB: https://github.com/AlexeyAB/darknet/blob/101de2b07aa2feefa74f7e73876fd5cc8fc696cf/src/detector.c#L1032

**Comment by ahsan856jalal** [comment]
Thank you @AlexeyAB
