### ISSUE TITLE
how to tell the value of num_of_clusters (or anchor) is better ? 

### ISSUE THREAD

**Issue by goodtogood** [AlexeyAB/darknet#501]
@AlexeyAB 
firstly, thank you so much for this great fork!
currently I want to calculate anchors for my custom data,
the size of network is 512, num_of_clusters might be 5-9, so making anchors using command below

> darknet detector calc_anchors ./my.data -num_of_clusters 5 -final_width 16 -final_heigh 16 -show

![5](https://user-images.githubusercontent.com/10088733/37865949-9b41fde8-2fbe-11e8-9fdd-e46a492eb225.jpg)

> darknet detector calc_anchors ./my.data -num_of_clusters 9 -final_width 16 -final_heigh 16 -show

![9](https://user-images.githubusercontent.com/10088733/37865950-a05f083e-2fbe-11e8-975c-6c0ade1b03a1.jpg)

how to tell which one is better ?
it might be a newbie question , sorry for that.
thanks!

**Comment by AlexeyAB** [comment]
@goodtogood Hi,

Just look at IoU for each calculation.
So calculate anchors for 5, 7, 9, 11 anchors and compare IoU. When increasing of number_of_clusters gives you low increasing in IoU, then you shouldn't increase number_of_clusters more.
For PascalVOC or MS COCO datasets optimal number_of_clusters is 5, because 6 doesn't give much advantage.

![image](https://user-images.githubusercontent.com/4096485/37868483-1270fbfa-2fb8-11e8-8b80-feae066ed503.png)

**Comment by goodtogood** [comment]
That is to say we cann't draw a conclusion from attached images directly, the key is IoU .
thank you so much!
