### ISSUE TITLE
Training data using Google Colab

### ISSUE THREAD

**Issue by Nazrindino97** [AlexeyAB/darknet#5128]
I want to train my own custom data using google colab and get stuck at this phase

```
%cd /content/drive/My Drive/darknet
!./darknet detector train data/obj.data cfg/yolov3-obj.cfg darknet53.conv.74
```

> /content/drive/My Drive/darknet
> /bin/bash: ./darknet: No such file or directory

One more question, the level (txt file) of every image that wants to be trained, does it need to include in the same file as images?

**Comment by Sunfl4wer** [comment]
I think the problem is you changed the directory to the `darknet` folder on your drive. 
After copying your darknet folder to colab's virtual machine. You need to change to the directory of that folder and compile darknet. The compiled version of darknet will be on the virtual machine not your drive. So because you changed the working directory to your drive you can not use the compiled program. You can use `!pwd` to know your current working directoy and `!ls` to see the sub-folder in it.
Also you do have to put the text file in the same folder with your image folder.

**Comment by Nazrindino97** [comment]
Thank you, got it!
