### ISSUE TITLE
Error load train.txt in google colab

### ISSUE THREAD

**Issue by Nazrindino97** [AlexeyAB/darknet#5133]
after it trained, it gets stuck at open the train.txt where the directory of all image and label were placed.

in train.txt
> ....
> data/obj/IMG_0049.JPG
> data/obj/IMG_0057.JPG
> data/obj/IMG_0065.JPG
> data/obj/IMG_0073.JPG

after run this line
`!./darknet detector train data/obj.data yolov3-palmoil.cfg darknet53.conv.74 -dont_show`

the error said

> Loading weights from darknet53.conv.74...Done!
> Learning Rate: 0.001, Momentum: 0.9, Decay: 0.0005
> Couldn't open file: data/train.txt

**Comment by Sunfl4wer** [comment]
There might be two ways to address this problem.

1. You didn't put the `train.txt` file in `data` folder which can be solved by a few copy and paste commands.
2. You use window and a IDE or text editor to edit `train.txt` and save it on Windows. The file format for window might not be able to be opened on Colab virtual machine since the OS is Ubuntu. You can install `dos2unix` and convert the file to UNIX format. These lines will installed dos2unix and convert all the text file in your directory to UNIX format:
`!sudo apt-get install dos2unix`
`!find . -type f -name "*.txt" -print0 | xargs -0 dos2unix`
Also if you have trouble with the `.cfg`, `.names` and `.data` files then convert them to UNIX format would help.
