### ISSUE TITLE
Different anchors mask between yolov3.cfg and csresnext50-panet-spp.cfg

### ISSUE THREAD

**Issue by bill97385** [AlexeyAB/darknet#5134]
Hi all

I found there are some small different setting masks

from yolov3.cfg

start at 6,7,8
`[yolo]`
`mask = 6,7,8`

from csresnext50-panet-spp.cfg

start at 0,1,2
`[yolo]`
`mask = 0,1,2`

is that mean csresnext50 should start from small anchors or just some mistake???

**Comment by WongKinYiu** [comment]
It just because yolov3 use FPN-like model (top-down), and csresnext50-panet-spp use PAN-like model (top-down -> bottom-up).

yolov3: 1x -> 2x -> 4x -> 8x -> 16x -> 32x -> (start top-down) -> **32x -> (predict 0,1,2)** -> **16x -> (predict 3,4,5)** -> **8x -> (predict 6,7,8)**

csresnext50-panet-spp: 1x -> 2x -> 4x -> 8x -> 16x -> 32x -> (start top-down) -> 32x -> 16x -> 8x -> (start bottom-up) -> **8x -> (predict 6,7,8)** -> **16x -> (predict 3,4,5)** -> **32x -> (predict 0,1,2)**

**Comment by bill97385** [comment]
Got it!!

Many thanks
