### ISSUE TITLE
What's the different between  Darknet here and the official one?

### ISSUE THREAD

**Issue by XP-CHRC** [AlexeyAB/darknet#529]
Hi,everyone, I run the same yolov2-tiny.cfg and yolov2-tiny.weights in the same device(jetson tx2), but the darknet download here is faster than the official one. So what's the difference between them?
Thanks.

**Comment by AlexeyAB** [comment]
Hi,

Did you use `./darknet detector demo`... command?

There are many changes such as:
* added support for Windows
* improved performance of `darknet detector demo`... for detection on the video (file/strem)
* improved performance of data augmentation for training (using OpenCV SSE/AVX functions instead of hand-written functions)
* added correct calculation of mAP, F1, IoU, Precision-Recall using command `darknet detector map`...
* added drawing of chart of average loss during training
* added calculation of anchors for training
* added example of Detection and Tracking objects: https://github.com/AlexeyAB/darknet/blob/master/src/yolo_console_dll.cpp
* many other fixes of code

And added manual How to train yolo.

**Comment by RushNuts** [comment]
How much fps on tx2?

**Comment by XP-CHRC** [comment]
@AlexeyAB yes, i used  ./darknet detector demo... command, and i want to know what make the demo faster here than the official one? Did you implement some optimization tricks?
thanks for your reply，you are so 牛逼！

**Comment by XP-CHRC** [comment]
@RushNuts  416*416 About 15fps, less than 20, without any optimizations. and what's more the speed depend on the quality of the video , i don't know why?

**Comment by AlexeyAB** [comment]
@XP-CHRC 

15 fps on TX2 using this fork? 
And how much fps on TX2 using original fork for `yolov2-tiny.cfg`?


There is optimization in resizing video frame to the network size, I just use OpenCV implementation `cvResize()` instead of hand-written implementation - it was a bottleneck - perfomance depends on initial resolution of video: https://github.com/AlexeyAB/darknet/blob/d0039f6dfd749feb8ef0be9137d6d19058093933/src/demo.c#L64-L65

https://github.com/AlexeyAB/darknet/blob/d0039f6dfd749feb8ef0be9137d6d19058093933/src/image.c#L874

**Comment by gangyahaidao** [comment]
this darknet is faster, it's true! Then i am confused, Why don't official projects adopt this project's advantages?
A Great Job, Thanks @AlexeyAB

**Comment by XP-CHRC** [comment]
@AlexeyAB Input size: 416*416, about 10fps on tx2 when use the original fork for yolov2-tiny.cfg. 
thanks for your jobs and reply.

**Comment by RushNuts** [comment]
@XP-CHRC Oh, 15fps. Not bad. What's resolution your input video?
