### ISSUE TITLE
0% GPU usage on Jetson Nano

### ISSUE THREAD

**Issue by marcoslucianops** [AlexeyAB/darknet#5327]
Hi,

I'm getting 0% GPU usage (GR3D_FREQ 0%) on NVIDIA Jetson Nano when I use command:

```
./darknet detector demo cfg/coco.data yolov3-tiny-prn.cfg yolov3-tiny-prn.weights video4k.mp4 -dont_show -out_filename res.mp4
```

![image](https://user-images.githubusercontent.com/47423225/80296232-7f87e500-874f-11ea-844d-5fc3d179d43d.png)

My Makefile:

```
GPU=1
CUDNN=1
CUDNN_HALF=0
OPENCV=1
AVX=0
OPENMP=1
LIBSO=0
ZED_CAMERA=0 # ZED SDK 3.0 and above
ZED_CAMERA_v2_8=0 # ZED SDK 2.X

USE_CPP=0
DEBUG=0

ARCH= -gencode arch=compute_53,code=[sm_53,compute_53]
...
```

And demo.c (changed to H264):
```
        output_video_writer =
            create_video_writer(out_filename, 'H', '2', '6', '4', src_fps, get_width_mat(det_img), get_height_mat(det_img), 1);
```

How can I solve this?

**Comment by AlexeyAB** [comment]
do
```
make clean
make
```

and run
`./darknet detector demo cfg/coco.data yolov3-tiny-prn.cfg yolov3-tiny-prn.weights video4k.mp4 -dont_show`

What AVG_FPS and GPU-usage do you get?

**Comment by marcoslucianops** [comment]
> What AVG_FPS and GPU-usage do you get?

GPU usage (GR3D_FREQ) oscillates constantly:

![image](https://user-images.githubusercontent.com/47423225/80310593-f48c0680-87b1-11ea-9449-5eec1eecb7a3.png)

**Comment by AlexeyAB** [comment]
Show such screenshot
![image](https://user-images.githubusercontent.com/4096485/80310986-fb347100-87e5-11ea-9722-ef943645a09e.png)

**Comment by marcoslucianops** [comment]
> Show such screenshot

![image](https://user-images.githubusercontent.com/47423225/80311501-5babba00-87b6-11ea-97b1-b0ff374564c5.png)

**Comment by AlexeyAB** [comment]
Your compilation is good enough.
So on Jetson Nano:
* with flag `-out_filename res.mp4` you get ~1 FPS
* without flag `-out_filename res.mp4` you get ~10 FPS

Instead of `'D', 'I', 'V', 'X'` in line https://github.com/AlexeyAB/darknet/blob/6033baabc9d646b23d8dbdb21cf84663910dca60/src/demo.c#L227
try to use other codecs: https://github.com/AlexeyAB/darknet/blob/6033baabc9d646b23d8dbdb21cf84663910dca60/src/demo.c#L229-L235

or use without flag `-out_filename res.mp4`
