### ISSUE TITLE
   0  illegal instruction (core dumped)

### ISSUE THREAD

**Issue by Stephenfang51** [AlexeyAB/darknet#5546]
after command like
`./darknet detector train ./build/darknet/x64/data/obj.data ./cfg/yolo-obj.cfg ./build/darknet/x64/yolov4.conv.137
`

errors occured

``` 
CUDA-version: 10000 (10020), cuDNN: 7.6.3, GPU count: 1  
 OpenCV version: 3.4.10
yolo-obj
 compute_capability = 610, cudnn_half = 0 
net.optimized_memory = 0 
mini_batch = 4, batch = 64, time_steps = 1, train = 1 
   layer   filters  size/strd(dil)      input                output
   0  illegal instruction (core dumped)
```

any advise ? Thank you Sir !

**Comment by silverlining21** [comment]
HI, how did you solve it?  i come across the same issue. could give me some advices.

**Comment by silverlining21** [comment]
I fix it by using `make` to replace `build.sh`, with `Makefile` configation as follow:
I'm using `ubuntu16.04 LTS`

GPU=1
CUDNN=1
CUDNN_HALF=1
OPENCV=1
AVX=0       ###### this line matters a lot.
OPENMP=1
LIBSO=1
ZED_CAMERA=0 # ZED SDK 3.0 and above
ZED_CAMERA_v2_8=0 # ZED SDK 2.X

**Comment by NeuroRoboticTech** [comment]
I am running into this same problem on multiple different machines. On one system I had darknet running fine with an older version. I pulled the latest master and ran the build.sh file. It compiled fine, but darknet does not run. It just dies immediately with the "illegal instruction (core dumped)" output. I tried modifying the makefile as stated above, but even though it compiles fine through cmake, it fails to compile with make. Below is the output I am getting. It is using the same opencv, so I am not sure why it would work for one and not the other. I also tried several things in the cmake file to try and turn off avx, but none of those worked. I am hoping someone has some suggestions to try because I am running out of ideas. Thanks.

Here is the output after compiling with cmake:
CUDA-version: 10010 (10010), cuDNN: 7.6.4, GPU count: 2  
 OpenCV version: 4.1.1
Demo
 0 : compute_capability = 610, cudnn_half = 0, GPU: TITAN X (Pascal) 
net.optimized_memory = 0 
mini_batch = 1, batch = 32, time_steps = 1, train = 0 
   layer   filters  size/strd(dil)      input                output
   0 Illegal instruction (core dumped)


Here is my attempt to use make:
make
chmod +x *.sh
g++ -std=c++11 -std=c++11 -Iinclude/ -I3rdparty/stb/include -DOPENCV `pkg-config --cflags opencv4 2> /dev/null || pkg-config --cflags opencv` -DGPU -I/usr/local/cuda/include/ -DCUDNN -DCUDNN_HALF -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -fPIC -Ofast -DOPENCV -fopenmp -DGPU -DCUDNN -I/usr/local/cudnn/include -DCUDNN_HALF -fPIC -c ./src/image_opencv.cpp -o obj/image_opencv.o
./src/image_opencv.cpp: In function ‘void draw_detections_cv_v3(void**, detection*, int, float, char**, image**, int, int)’:
./src/image_opencv.cpp:926:23: warning: variable ‘rgb’ set but not used [-Wunused-but-set-variable]
                 float rgb[3];
                       ^
./src/image_opencv.cpp: In function ‘void cv_draw_object(image, float*, int, int, int*, float*, int*, int, char**)’:
./src/image_opencv.cpp:1417:27: error: ‘waitKeyEx’ is not a member of ‘cv’
         int pressed_key = cv::waitKeyEx(20); // OpenCV 3.x
                           ^
compilation terminated due to -Wfatal-errors.
Makefile:174: recipe for target 'obj/image_opencv.o' failed
make: *** [obj/image_opencv.o] Error 1

**Comment by NeuroRoboticTech** [comment]
I was able to test this on my other system that was rebuilt with all the latest opencv, cuda, cudnn, etc.. and the makefile worked on it and on my TX2. So my other problem must have been something with the configuration of that older system. Nothing I tried would get the cmake file to work though, only make. It would be nice if that was fixed. Thanks.
