### ISSUE TITLE
Problem with predict_classifier

### ISSUE THREAD

**Issue by phqmourao** [AlexeyAB/darknet#5810]
Hi Alexey,

I have a problem when trying to execute the following command:
darknet.exe classifier predict data/obj.data darknet53.cfg darknet53.weights < data/test.txt

If one of the images in the file "test.txt" has the same dimensions (width and height) as the network resolution (net.w and net.h), the program is terminated and the remaining images are not evaluated.

I think the problem may be related to this code in "classifier.c":
Line 847: image resized = resize_min(im, net.w);
Line 869: free_image(resized);

The problem does not occur if Line 869 is commented.

**Comment by imaami** [comment]
There's indeed a double `free()` bug in `predict_classifier()` which only happens when the resized image size would be the same as the original.

Lines 844 and 845:

```
        image im = load_image_color(input, 0, 0);
        image resized = resize_min(im, net.w);
```

`resize_min()` in `src/image.c` checks what the new size would be, and if it's the same as the input image size, it won't allocate a new image buffer, but will instead return a reference to the input image.

Therefore when we arrive at line 866 in `predict_classifier()`, this will try to free the same data pointer twice:

```
        free_image(im);
        free_image(resized);
```

Lots of fun little suprises to be found inside darknet.

**Comment by imaami** [comment]
@AlexeyAB could you merge #5933?

**Comment by AlexeyAB** [comment]
@imaami Hi,

> See the second line there? The resize_min() function in src/image.c checks what the new size would be, and if it's the same as the input image size, it won't allocate a new image buffer, but will instead return a reference to the input image.

So may be we should fix `resize_min()` function instead of other part of code?
So `resize_min()` will have the same behavior for all cases in all parts of codes. I think it will be much more stable.

**Comment by AlexeyAB** [comment]
This is fixed.
