### ISSUE TITLE
Question OPENCV for inference

### ISSUE THREAD

**Issue by sealedtx** [AlexeyAB/darknet#5938]
Hi @AlexeyAB ! Thank you again for a great work with darknet! I have a question:
What is the use of OPENCV for inference? Do I need to keep compiling it with opencv if I just run detection with python and don't train? Or it could be disabled without impact on performance? Thank you!

**Comment by AlexeyAB** [comment]
If you want to use OpenCV-dnn (possibly with OpenVINO backend)
then you should use OpenCV instead of Darknet: https://docs.opencv.org/master/da/d9d/tutorial_dnn_yolo.html

C++ example: https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.cpp
Python example: https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.py

**Comment by sealedtx** [comment]
@AlexeyAB No, I mean build darknet library with OPENCV=1 in Makefile, is it used for inference in python? Or just for training augumentation and c++ inference (like demo.cpp)?

**Comment by AlexeyAB** [comment]
OpenCV-dnn isn't used for inference in the Darknet.

OpenCV is used for pre/post-processing in the Darknet (like demo.cpp) and 
* in the darknet_video.py https://github.com/AlexeyAB/darknet/blob/master/darknet_video.py

* and in the darknet.py if you un-comment it https://github.com/AlexeyAB/darknet/blob/master/darknet.py#L260-L268

**Comment by sealedtx** [comment]
ok, thank you for clarifying
