### ISSUE TITLE
Detection depends upon position in image.

### ISSUE THREAD

**Issue by rbgreenway** [AlexeyAB/darknet#6631]
I am trying to use YoloV4 to perform OCR in a small image (256 x 128)...yes, it's LPR.  As you'd expect, all the characters are about the same size.  The training went fine, but it seems the detections are dependent on where the letters appear horizontally in the image.  This suggests to me that I don't have enough horizontal resolution in the output feature map...which I'm guessing is 256/32 = 8 in the horizontal and 128/32 = 4 in the vertical.  In order to test this, I incrementally translated the image to the right to see what effect it would have on the detections.  

The image below shows what happened.  

![p](https://user-images.githubusercontent.com/2991932/92553876-b86db580-f229-11ea-948b-ae4e09b0e5e2.png)

So, this leaves me with a couple of questions:
1) am I interpreting this correctly, in that I need more resolution in the feature map?  
2) if so, how do I set this up in the config file?

I guess, worst case I could just scale up the image.

I did use the darknet tool for calculating the anchors from my dataset of images.

here's my config file (had to add the ".txt" to get it to upload):

[yolov4_lpocr.cfg.txt](https://github.com/AlexeyAB/darknet/files/5192593/yolov4_lpocr.cfg.txt)

here's the chart.png after training:

![chart](https://user-images.githubusercontent.com/2991932/92554711-95440580-f22b-11ea-830a-45a7f58b304e.png)

Any suggestions would be appreciated.

**Comment by stephanecharette** [comment]
Whenever someone says they calculated custom anchors, I normally ignore the post.  I've never seen it be necessary in any of the projects I've done, and it normally indicates a host of problems which is for obviously very advanced users.  And I don't consider myself advanced enough to have done it!

But this time I'll bite.  Because I also have done something similar with license plates.  (https://www.ccoderun.ca/programming/ml/iranian_plates.html)

One thing to remember is if you want Darknet to detect it, then it must be in the training image.  Sounds simple, right?  But this applies to position within the image.  So if the letter 'D' never appears on the very left of the image in your training data, then it won't be found.  Most likely, you don't have enough variation in your training data.

The image size of 256x128 is fine, that's not your problem.  As long as your network matches.  What size are you using for the network?

Did you remember to turn off the left/right mirror image flip in your .cfg file?  In the `[net]` section, you have to put `flip=0`.  Otherwise you'll run into problems where 'E' looks similar to '3' when flipped, etc.

Your chart shows you trained for 50K iterations, which is good.  I just checked, and my license plate project which uses YOLOv3-Tiny was only trained for 20K.  But I guess this brings up another point -- do you have multiple states?  All using different fonts and colours?  Or are you limited to Pennsylvania?  Especially if you have multiple states, Canada, Mexico, what did you use for saturation, exposure, and hue?

**Comment by rbgreenway** [comment]
Thanks for the comments, Stephan.
I've resized anchors many times with good success.  I'm absolutely not saying I know what I'm doing there, but I felt like I had to since most of the standard anchors were larger than my entire image size.
Network size = 256x128 to match all incoming images.  I don't have a "flip" in the [net] section of my cfg file (yolov4), but I could try adding flip=0 to that section and see what happens.
I've got 100K+ synthesized images in my training set.  Including 17 different fonts (which are specifically matched to fonts used by states), generate random characters, and randomly apply noise, warping, translation, rotation, blurring, vary bkg/foreground colors, etc.  The appearance of each of the 35 characters is evenly distributed across the dataset. I don't think it's the training dataset, but I could be wrong.  It's always good to have another set of eyes and suggestions when it comes to these things.
The offset testing I did for the 1 license plate I showed in the gallery of pictures above was repeated for several different plate images.  All gave the same results...the characters detected changed as I slid the image horizontally... and when it detected, the confidence was 0.98+.  It didn't seem to be related to any specific character.
I did find another darknet network for LPR, but it wasn't a "yolo" network and was beyond my comprehension to understand what was going on with it.  The developer specifically mentioned that he had to increase the horizontal resolution in his feature map in order to get it to work.  As you know, the standard 416x416 yolo has a 13x13 feature map.  In his custom network, he claimed a 30x10 feature map for a 240x80 network size.  This is where I got the idea.  His config file is given below (he shared on github):

[ocr.cfg.txt](https://github.com/AlexeyAB/darknet/files/5195937/ocr.cfg.txt)

Notice that it doesn't follow the "yolo" rule for being a multiple of 32.  He somehow has used a multiple of 8...so his feature map size is found by:  240/8= 30  and 80/8 = 10 --> 30x10.  

It seems there's a way to do this, but I'm just not smart enough to figure it out.  Hence the question... :-)

**Comment by rbgreenway** [comment]
Thanks for the comments, Stephan.
I've resized anchors many times with good success.  I'm absolutely not saying I know what I'm doing there, but I felt like I had to since most of the standard anchors were larger than my entire image size.
Network size = 256x128 to match all incoming images.  I don't have a "flip" in the [net] section of my cfg file (yolov4), but I could try adding flip=0 to that section and see what happens.
I've got 100K+ synthesized images in my training set.  Including 17 different fonts (which are specifically matched to fonts used by states), generate random characters, and randomly apply noise, warping, translation, rotation, blurring, vary bkg/foreground colors, etc.  The appearance of each of the 35 characters is evenly distributed across the dataset. I don't think it's the training dataset, but I could be wrong.  It's always good to have another set of eyes and suggestions when it comes to these things.
The offset testing I did for the 1 license plate I showed in the gallery of pictures above was repeated for several different plate images.  All gave the same results...the characters detected changed as I slid the image horizontally... and when it detected, the confidence was 0.98+.  It didn't seem to be related to any specific character.
I did find another darknet network for LPR, but it wasn't a "yolo" network and was beyond my comprehension to understand what was going on with it.  The developer specifically mentioned that he had to increase the horizontal resolution in his feature map in order to get it to work.  As you know, the standard 416x416 yolo has a 13x13 feature map.  In his custom network, he claimed a 30x10 feature map for a 240x80 network size.  This is where I got the idea.  His config file is given below (he shared on github):

[ocr.cfg.txt](https://github.com/AlexeyAB/darknet/files/5195937/ocr.cfg.txt)

Notice that it doesn't follow the "yolo" rule for being a multiple of 32.  He somehow has used a multiple of 8...so his feature map size is found by:  240/8= 30  and 80/8 = 10 --> 30x10.  

It seems there's a way to do this, but I'm just not smart enough to figure it out.  Hence the question... :-)
