### ISSUE TITLE
training for custom object detection yolo3 which cfg to use

### ISSUE THREAD

**Issue by shahla-ai** [AlexeyAB/darknet#6885]
@AlexeyAB 
I know that this is a repeated question I have been here for nearly tow months I need a confirmation.
my objective is to make custom object detection on CPU devices.
the training part is performed on google colab (training with GPU).
after some research I focused on yolo3  since yolo4 needs GPU due to the exponential in mesh activation function.
since I only need to detect single object Iam using yolo3-tiny cfg
I followed the instructions for training for custom objects yet I am confused about which is the best tiny yolo3 model to be used for custom object detection. 
in an old issue you mentioned that yolov3-tiny-prn is the best in yolo3 tiny and in another issue 4009 you referred to another cfg model.
 can you please confirm which is the best cfg for single object detection using only cpu hardware.
For testing Iam using NFPA DATASET since it doesn't contain noise. I am using yolov3-tiny-prn cfg

**Comment by shahla-ai** [comment]
I also calculated the anchers of the NFPA dataset

**Comment by stephanecharette** [comment]
> after some research I focused on yolo3 since yolo4 needs GPU due to the exponential in mesh activation function.
> since I only need to detect single object Iam using yolo3-tiny cfg

That is not true.  I use YOLOv4 on CPU all the time, including in some VMs that have no access to a GPU.

> I followed the instructions for training for custom objects yet I am confused about which is the best tiny yolo3 model to be used for custom object detection.

It depends on what you want to do.  Normally I use YOLOv4-tiny because it is fastest.  But if the objects are particularly small (getting close to the 16x16 limit once the image is resized to the dimensions of the network) then I switch to YOLOv4-tiny-3l, which has 3 YOLO layers instead of 2 in "tiny".

I don't have much details on the different .cfg files, but what I found I put in a table here:  https://www.ccoderun.ca/darkmark/Configuration.html

**Comment by shahla-ai** [comment]
Hi 

> That is not true. I use YOLOv4 on CPU all the time, including in some VMs that have no access to a GPU.

Thank you for your important information

> It depends on what you want to do. Normally I use YOLOv4-tiny because it is fastest. But if the objects are particularly small (getting close to the 16x16 limit once the image is resized to the dimensions of the network) then I switch to YOLOv4-tiny-3l, which has 3 YOLO layers instead of 2 in "tiny".

i want a model to detect a single object (my be small) that have a good performance on embedded devices (RPI4) or Intel CPU Core i3 for example, but with the best mAP possible.I found yolov3-tiny-prn.cfg architecture very close to what i want as @AlexeyAB said, but my question is that is there anything better for my case ?

**Comment by stephanecharette** [comment]
I cannot speak for AlexeyAB.  But here is 1 example of a project I did using RPI:

https://www.ccoderun.ca/programming/ml/people_counter.html

> that have a good performance on embedded devices

The term "good performance" is open to interpretation.  What kind of numbers do you need?  What network size?  What FPS?

**Comment by shahla-ai** [comment]
> I cannot speak for AlexeyAB. But here is 1 example of a project I did using RPI:

impressive results, what FPS did this model give and what what version of RPI ? can you tell me what is the .cfg file used?
i need FPS ~ 15 or more (not necessarily on RPI), any network size to give me the FPS i need, with single object of size >~ 32x32 when the image is resized to 416x416.
i will be pleasured if you correct for me any wrong concept i have.

**Comment by stephanecharette** [comment]
> what what version of RPI ?

I don't know which model RPI the client was using in this case.

> can you tell me what is the .cfg file used?

That one was yolov3-tiny.cfg, because the project was done before yolov4 was available.

> i need FPS ~ 15 or more

Good luck with that on an embedded device like a RPI!  With my Jetson Nano and a USB camera at 800x600 with a YOLO network defined as 800x608, I think I was getting ~2 FPS.  I have since switched to a NVidia Xavier NX for embedded devices.

> with single object of size >~ 32x32 when the image is resized to 416x416.

YOLOv4-tiny.cfg is what I would use if your images are 416x416 and the objects to find are ~32x32.
