### ISSUE TITLE
What cfg file to use for "CSP-p7 + Mish (multi-scale)" model?

### ISSUE THREAD

**Issue by ievbu** [AlexeyAB/darknet#6916]
In [CSPNet: A New Backbone that can Enhance Learning Capability of CNN](https://paperswithcode.com/paper/cspnet-a-new-backbone-that-can-enhance) I see darknet as official repository for "CSP-p7 + Mish (multi-scale)" model for object detection. I want to train this model ("CSP-p7 + Mish (multi-scale)") but I don't see a cfg file named like this architecture or any similar name. What cfg file should I use?

**Comment by AlexeyAB** [comment]
It is trained on this repository https://github.com/WongKinYiu/PyTorch_YOLOv4


----

I just added similar but not identical cfg-files:
* Classifier: `cspx-p7-mish-omega.cfg` - should be trained ~1 month on GPU A100 https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/cspx-p7-mish-omega.cfg

* Detector: `cspx-p7-mish_hp.cfg` - should be trained ~1.5 months on GPU A100 https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/cspx-p7-mish_hp.cfg

Extract pre-trained weights from Classifier for training Detector:
`./darknet partial cfg/cspx-p7-mish-omega.cfg backup/cspx-p7-mish-omega_final.weights backup/cspx-p7-mish-omega_final.conv.207 207`


Also I will change `yolo_layer.c` for faster training, since currently it requires even longer training.

**Comment by ievbu** [comment]
Thank you for information!
