### ISSUE TITLE
Dockerfile on project

### ISSUE THREAD

**Issue by vanchung1995** [AlexeyAB/darknet#6960]
To anyone can run project without errors. I think you should write a Dockerfile for anyone running on docker instead of install dozens of libs

**Comment by AlexeyAB** [comment]
@cenit Hi,
Do you have experience building Dockerfiles for different OS?

**Comment by vanchung1995** [comment]
It's regret that I don't. :(

**Comment by ywssng** [comment]
@vanchung1995 Start from ufoym/deepo:darknet image, and follow the instruction guide of this repo. It worked for me.

**Comment by bizmate** [comment]
@AlexeyAB there should be no need to build docker images for different OSs. Docker images are not specific for each OS. You just need to configure nvidia drivers accordingly if you have a GPU. I am using a docker image already because darknet is extremely difficult to get it working on a host machine as several bugs can happen in configuring openCV, cuda etc ...

This project already contains a darknet version fully dockerised and i keep using it since darknet on my machine always gives problems.

https://github.com/daisukekobayashi/darknet-docker

and here are examples of how I use it in a very rudimentary way that just does work for me to delete files without people

https://github.com/bizmate/bash-essentials/blob/master/bin/darknet-detect-and-trash.sh#L74-L81
