### ISSUE TITLE
Can’t use GPU for training or testing,

### ISSUE THREAD

**Issue by chenmingguo** [AlexeyAB/darknet#7024]
I used CUDA 10.2，cudnn 7.6.5，GPU NVIDIA GeForce RTX 2060

I have set up in Makefile 
GPU=1
CUDNN=1
ifeq ($(GPU), 1)
COMMON+= -DGPU -I/usr/local/cuda-10.2/include/
CFLAGS+= -DGPU
LDFLAGS+= -L/usr/local/cuda-10.2/lib64 -lcuda -lcudart -lcublas -lcurand

 C:\Yolo-Fastest\build\darknet\x64>  ./darknet.exe detector test ./cfg/voc.data ./cfg/yolo-fastest.cfg ./cfg/yolo-fastest.weights ./data/person.jpg -i 1 -thresh 0.25 -out_filename ./data/person_output.jpg

CUDA status Error: file: c:\yolo-fastest\src\dark_cuda.c : cuda_set_device() : line: 39 : build time: Nov 24 2020 - 18:36:35
CUDA Error: invalid device ordinal

Can anyone help to fix this?

**Comment by LeKristapino** [comment]
I think your command is wrong - `-i` argument if I'm not mistaken, is used for multi-GPU support. And since devices are 0-indexed and you have put `-i 1` in your command, CUDA is looking for a second GPU, which probably doesn't exist. Either change it to `-i 0` or I think ommit the argument completely as it will use the GPU by default

**Comment by chenmingguo** [comment]
You are right, I set the wrong command, set the device with more GPU
Thank you very much, you saved me and helped me solve the problems that have troubled me for many days
