### ISSUE TITLE
BNN || XOR-net

### ISSUE THREAD

**Issue by johnnydept** [AlexeyAB/darknet#756]
HI @AlexeyAB , 

Good day, i read the [paper](https://pjreddie.com/media/files/XNOR_ECCV2.pdf) that Ali and Pjreddie did on BNN and XOR. Is darknet (yolov2/yolov3) still support BNN/XOR?

**Comment by AlexeyAB** [comment]
@johnnydept Hi,

No, Darknet doesn't support fully BNN/XNOR. `xnor_layer.c` was removed at 25.09.2016. 

* You can try to use this commit, but I don't know does it work well: https://github.com/AlexeyAB/darknet/tree/8a767f106677b78a389e1ceffc066501015ec51a
    There are `xnor_layer.c` and `binary_convolution.c`, but this commit supports Yolo v1 only.

* Or you can try to use current last commit and add params `xnor=1` for each `[convolutional]` layer **except 1-st and last**, but it will reduce speed and accuracy - it will quantized float-32 to bit-1 for each layer and still calculate convolution using float-32. I can't get good result for default model `tiny-yolo-voc.weights` that is trained using float-32 and quantized (1-bit) only for Detection as said Joseph: https://github.com/pjreddie/darknet/issues/556

* Or you can train your own model using cfg-file like this: [Uploading tiny-yolo-obj_xnor.zip…]()
I just trained this file for my dataset (6 classes and 15 000 images), and get mAP 57.82 (XNOR) instead of mAP 88.19 (float-32).

In the artice compare only Classification accuracy 44.2% instead of 56.7%, but **there is not Detection accuracy**: https://arxiv.org/pdf/1603.05279.pdf XNOR-net for Torch 7.0: https://github.com/allenai/XNOR-Net
But in this article showed that using **less than 4 bit does not have the optimal ratio of speed and accuracy**, at least for models Alexnet and VGG16: https://arxiv.org/pdf/1510.00149.pdf
So I think for much larger models like Yolo v2 / v3 should be used at least INT8/FP16.

----

May be I will add INT8 quantinization for Detection.

**Comment by johnnydept** [comment]
@AlexeyAB  Alright, Thanks Alex. I'm looking forward to it. (INT8)

**Comment by AlexeyAB** [comment]
@johnnydept I added XNOR-net for CPU if AVX is enabled in the Makefile: https://github.com/AlexeyAB/darknet/issues/1472
