### ISSUE TITLE
 detector map (yolo3) -> Segmentation fault 

### ISSUE THREAD

**Issue by Rus-L** [AlexeyAB/darknet#763]
When you start the detector map (yolo2) - everything works correctly, 
but when you start the detector map (yolo 3) error Segmentation fault http://prntscr.com/jetkbn

**Comment by AlexeyAB** [comment]
@Rus-L 

What command line do you use to get mAP for yolo v3?

**Comment by Rus-L** [comment]
I use the latest version of the repository. The network is trained on a custom dataset, and it works very well.
get mAP: ./darknet detector map obj.data yolov3-voc.cfg yolov3-voc_30000.weights
The problem is on two servers with GPU and one without GPU (all run on Ubuntu 16.04)
On the server without GPU, the error is slightly different.
After the list of classes there are two rows with empty classes
...
class_id = 5, name = (null), ap = 0.00%
class_id = 6, name = (null), ap = 0.00%
Segmentation fault (core dumped)

**Comment by AlexeyAB** [comment]
* What `classes=` in the each of **3** [yolo]-layers in your cfg-file?
* Can you show your `obj.data` and `obj.names` files?
* How many lines are in your `obj.names` file?
* Can mAP work if instead of this line: https://github.com/AlexeyAB/darknet/blob/6b8fd6f33f6a61138136fd022c2b887ae39e2c42/src/detector.c#L819
you use this line:
```cpp
printf("class_id = %d, \t ap = %2.2f %% \n", i, avg_precision*100);
```
