### ISSUE TITLE
v4-CSP implemented in darknet is way worse then the normal v4

### ISSUE THREAD

**Issue by bjajoh** [AlexeyAB/darknet#7800]
Hi,

I trained a custom dataset on different yolo models. However I'm a bit confused as the CSP version performs way way worse than any normal yolo. TO compare them better, I used a training size of 608*608 for both. v4 achieves a mAP of 57.9% while the CSP version only gets up to 44.5%. I find this a bit suspicious.

Do you have any idea what is going on here?

Thanks for your help!

**Comment by AbdullahAldosari** [comment]
In my experience the CSP versions don't work well when the objects you are trying to detect are small but the mAP difference that you are having seems a bit too much.

**Comment by bjajoh** [comment]
The objects are small, that is true, but I'm still wondering because CSP should be an improvement and difference is actually quite large.

**Comment by AbdullahAldosari** [comment]
CSP is an improvement on the COCO dataset because most of its objects are medium or large, even AlexeyAB commented on one of the issues saying that it doesn't perform well on small objects but I can't find it.

I am not sure though why the difference in mAP is large in your case I can't help you with that.

**Comment by bjajoh** [comment]
Interesting, if you or anyone could provide AlexeyAB comment on that, it would be really interesting!

**Comment by bjajoh** [comment]
Here it is: https://github.com/AlexeyAB/darknet/issues/7087#issuecomment-750924784
