### ISSUE TITLE
calc_mAP

### ISSUE THREAD

**Issue by 123liluky** [AlexeyAB/darknet#784]
Is calc_mAP.cmd suitable for tiny_yolo2? I  used it for tiny_yolo2 like this darknet.exe detector map data/obj.data cfg/tiny-yolo-obj.cfg backup/tiny-yolo-obj_25000.weights.And the result is strange. mAP =0.47%. But I see detections in each test figure are mostly correct. 
The accuracy value is more than 90% I test.

**Comment by AlexeyAB** [comment]
Yes, `detector map` is suitable for any Yolo model.
1. Can you show content of obj.data?
2. Can you show screenshot of mAP result?

**Comment by AlexeyAB** [comment]
> Why network with higher precision and recall gets lower mAP? I am confused.

I think, because you have more boxes on images with class (vein) than with class (artery). 

* `mAP = (ap(vein) + ap(artery) ) / 2 = ap(vein)*0.5 + ap(artery)*0.5` - this is an average value **for all APs**

* `precision, recall, IoU, F1` - are average values **for all Boxes**.
    So if vein-boxes are 90%, and artery-boxes 10%, then it can be `IoU = IoU(vein)*0.9 + IoU(artery)*0.1`

So you can choose, do you want to detect all classes well (get the weights with the highest mAP). Or do you want to detect classes well that occur more often (get the weights with the highest Precision, Recall, IoU).

**Comment by TaihuLight** [comment]
@123liluky @AlexeyAB 
How to generate coco_testdev file for calculating the mAP on COCO dataset? Because part of iamge in the valid dataset are not annotated.
