### ISSUE TITLE
image size for network and training

### ISSUE THREAD

**Issue by haviduck** [AlexeyAB/darknet#8057]
alright ive been working with yolo for the past some years and its been smaller projects and ive done allright. there are a few things ive never had a clear answer to without finding contradictive answers.

at this point ive gathered a dataset of 90.000 images that i am set to train and i gotta do it right. as these are rough, maritime images their quality isnt too good so ive kept a resolution 1920x1080.  which is huge compared to most wikis ive found. but thats the format of the videos and concidering im labeling tiny fish clustered inbetween larger fish, it had to be that way.

now heres where i still get lost: when i make my model, am i supposed to honor its letter box 1080p resolution or am i meant to use 832x832 etc. i know darknet resizes and all this, but when i use these portrait resolutions, i face accuracy issues.  whats the general rule of thumb for training resolution? and whats the correct way of handling inferencing after the fact?

a final little conondrum. lets say i train a set of pseudolabeled images. now after i train for a bit i relabel the same images and continue training the same model but with different annotations referencef in valid . will this create confusion in the network or will it prioritize my valid annotations?

ill be greatly happy for any input, im alone on this in a big company and my rubberduck has stopped talking to me.

**Comment by haviduck** [comment]
found a great post in the issues section. explained it all.

**Comment by akashAD98** [comment]
@haviduck can you please add that issue here? so others also get some idea

**Comment by stephanecharette** [comment]
If your training images and the images you use for inference are the same size, then it (mostly) doesn't matter.  Because the images will be stretched the exact same way your training images were also stretched, so everything matches.

Where it does matter is if you are trying to find small objects.  If the images are stretched in a way where the small objects are now so tiny they cannot possibly be found, then obviously this will be a problem.  In which case there are techniques for dealing with this, such as the tiling done by DarkHelp:  https://www.ccoderun.ca/darkhelp/api/Tiling.html

If the aspect ratio or the size of the images differs between the training images and the images you use for inference, then you need to be careful.  Darknet does a great job on relatively large objects.  But if the results aren't great, you may find you need to enable tiling (see previous link) or you need to crop some of the training/inference images to match the aspect ratio so the image is stretched in a similar manner.
