### ISSUE TITLE
YOLOv3-tiny in Darknet vs OpenCV DNN: large objects are missed

### ISSUE THREAD

**Issue by stephanecharette** [AlexeyAB/darknet#8146]
I trained a YOLOv3-tiny network using several dash-cam datasets.  I then run this network in the following 4 scenarios:

- Darknet (CPU)
- Darknet (CUDA)
- OpenCV DNN (CPU)
- OpenCV DNN (CUDA)

Other than the obvious timing differences, the results are nearly 100% identical.  With 1 exception:  when using OpenCV DNN -- both CPU and CUDA -- large objects seem to be missed.

Here is an example frame grab.  The two on the left are Darknet, the two on the right are OpenCV DNN:

![image](https://user-images.githubusercontent.com/5061352/136448404-656a3189-53fb-479b-aa49-55ff64b50c21.png)

Source:  https://www.youtube.com/watch?v=fFYV2uPt-XI

You can see even small objects like the traffic lights are detected correctly.  But the large vehicles in the foreground are missed.  Anyone know why large objects might be missed when using OpenCV DNN?

Network was trained using these options:

![image](https://user-images.githubusercontent.com/5061352/136449084-a3313350-eb88-4a92-859b-380746899777.png)

**Comment by stephanecharette** [comment]
@AlexeyAB Do you have any insight into why the same network would fail to detect large objects when running via OpenCV DNN vs Darknet?

**Comment by AlexeyAB** [comment]
It would be great if you can check which of these models produce different results in Darknet and OpenCV:  yolov4.weights, yolov4-csp-x-swish.weights and yolov4-tiny.weights  https://github.com/AlexeyAB/darknet#pre-trained-models

Initially when I added YOLOv2 to the OpenCV, I added tests to check that it produces identical results in both OpenCV and Darknet: https://github.com/opencv/opencv/pull/9705

Now **OpenCV>=4.5.4** supports **Scaled-YOLOv4** ( https://github.com/opencv/opencv/issues/18975 , https://github.com/opencv/opencv/pull/20671 , https://github.com/opencv/opencv/pull/20818 ) and all these models: https://github.com/AlexeyAB/darknet#pre-trained-models
And as I can see tests for YOLOv4 and Scaled-YOLOv4 are also used.

**Comment by stephanecharette** [comment]
> I was trying to use YOLO in OpenCV 4.5.0 but did run into similar problems.

Glad to see I'm not the only person running into this problem.  It has also been discussed several times on the Darknet/YOLO discord, but so far I don't know of anyone who knows how to solve the problem.

**Comment by AxelWS** [comment]
@stephanecharette If you mean the general problem (correct default parameters, which way of image resizing to use, which kind of NMS, etc.) I also don't know how to establish a reference implementation that can be used by darknet, DarkHelper, and everyone.

If you just ask how to get all yolo layer outputs from OpenCV, this did work for me:
&nbsp;&nbsp;std::vector&lt;cv::String> outputLayerNames;
&nbsp;&nbsp;for (cv::String const layerName : network->getLayerNames())
&nbsp;&nbsp;&nbsp;&nbsp;if (layerName.rfind("yolo_", 0) == 0) // if layerName starts with yolo
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;outputLayerNames.push_back(layerName);
&nbsp;&nbsp;std::vector&lt;std::vector&lt;cv::Mat>> outMats;
&nbsp;&nbsp;network->forward(outMats, outputLayerNames);	//compute output
And then collect results:
&nbsp;&nbsp;for (int outIndex = 0; outIndex &lt; int(outputLayerNames.size()); outIndex++)
&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;auto& outMat = outMats[outIndex][0];
[...]
&nbsp;&nbsp;}
Finally do NMS over all collected detections. Preserve class probabilities and "objectness" if desired. The way I understand it 1-objectness is kind of a rejection class probability. (By the way, getting correct probabilities out of darknet is tricky, because a) probabilities are already multiplied by objectness b) anything lower than thresh 0.2 is set to 0.0 and c) NMS in darknet sets some non-maximal probabilities to 0.0.)

**Comment by stephanecharette** [comment]
No, that's not what I mean.  See the top of this post for the problem.  This has been discussed on the discord server many times.  Everyone who tries to use YOLOv4-tiny when using OpenCV's DNN module is stuck with the exact same issue where larger objects are not detected.

**Comment by AxelWS** [comment]
Stéphane, I carefully read what this issue is about. Sorry for digressing into probabilities and other problems. My main point is: all OpenCV examples I find read output only from the last network layer, which is a YOLO layer. The tiny network I use has another YOLO layer in the middle. Darknet reads output from _both_ YOLO layers. So when using OpenCV's DNN you have to do that too.

**Comment by stephanecharette** [comment]
Oh...  I'm using `cv::dnn::Net::forward()` to get the output mat.  But you're saying that is just the very last YOLO layer, and I need to do the same thing with all the other YOLO layers?  Hmmm.  Maybe use the `forward()` that takes an array of mats?

Let me look into that.  Would be nice to finally understand what is going on and have this fixed!

**Comment by AxelWS** [comment]
Did you read the code I posted above? It did improve results for me.

**Comment by stephanecharette** [comment]
I didn't understand it.  Am attempting to figure it out now.  This is what I'm working with:  https://github.com/stephanecharette/DarkHelp/blob/master/src-lib/DarkHelpNN.cpp#L1044

**Comment by stephanecharette** [comment]
@AxelWS Thank you so much!  Got it working.  That was the key point, to take the output from all the yolo layers instead of just the last one.  I'll update DarkHelp with these changes later tonight.
