### ISSUE TITLE
Model trained on your fork much bigger on official repo

### ISSUE THREAD

**Issue by louisondumont** [AlexeyAB/darknet#817]
I trained a model using your fork. When loaded in RAM, it uses approximately 900MB.

When I run the same model with the same .cfg file on the official darknet repo, it uses approx 4GB of ram. Why's that?

Thanks!

**Comment by AlexeyAB** [comment]
Both repo use mini-batch=1 for detection.
But original repo allocates GPU-memory for the whole mini-batch = `batch / subdivision` even for detection altghough it uses only mini-batch=1 for inference, while my repo allocates and uses mini-batch = 1.

More about differences: https://github.com/AlexeyAB/darknet/issues/529#issuecomment-377204382

**Comment by louisondumont** [comment]
Thanks! What part of the code on the original repo should I change in order to have the same performances as with your code?

**Comment by AlexeyAB** [comment]
There are 419 commits ahead.

At least your should implement:

1. `network parse_network_cfg_custom(char *filename, int batch)` instead of `network parse_network_cfg(char *filename)` - to reduce GPU-memory usage for detection

2. Also implement `void fuse_conv_batchnorm(network net)` **+7% speedup inference**

3. To **speedup 2x** detection on high resolution video - you should implement `image get_image_from_stream_resize(CvCapture *cap, int w, int h, IplImage** in_img, int cpp_video_capture)` to  without it you can't utilize 100% of middle/high-end GPU on 2K-4K video stream and you can't detect in realtime

4. Get my `forward_convolutional_layer_gpu()` and  `backward_convolutional_layer_gpu()` if you want to speedup **3x detection and 2x training** using Tensor Cores

5. `image image_data_augmentation(IplImage* ipl, int w, int h, int pleft, int ptop, int swidth, int sheight, int flip,float jitter, float dhue, float dsat, float dexp)` to **speedup data augmentation 3.5x**, without it you can't train on highend multi-GPUs.

0. `gemm_nn()` if you want to use detection on CPU with AVX ~+85% speed

and other features...

**Comment by louisondumont** [comment]
I see. I already have a python script that uses libdarknet.so on the official repo. I'd like to use your repo instead. Do you have any Python script that I could use with your repo?

**Comment by AlexeyAB** [comment]
In the main directory: 
https://github.com/AlexeyAB/darknet/blob/master/darknet.py

**Comment by louisondumont** [comment]
Great thank you!
