### ISSUE TITLE
Don't want the output prediction window to be displayed

### ISSUE THREAD

**Issue by sabinajashir** [AlexeyAB/darknet#8250]
Hi everyone,
I am trying to edit the code so that it doesn't show the output prediction image with bounding boxes. The code should just continue after displaying the confidence of different labels in terminal. How should I do that?

**Comment by stephanecharette** [comment]
Do you mean:  https://www.ccoderun.ca/programming/darknet_faq/#json_output ?

**Comment by sabinajashir** [comment]
![WhatsApp Image 2021-11-17 at 8 39 23 AM](https://user-images.githubusercontent.com/81210620/143199738-0e54eba3-5d96-408f-97c0-779c0f421316.jpeg)

**Comment by sabinajashir** [comment]
thank you for your reply..I dont want this prediction window to be displayed.

**Comment by stephanecharette** [comment]
...?  Did you follow the link I provided?

**Comment by sabinajashir** [comment]
Yes sir, But that's for getting the json output

**Comment by stephanecharette** [comment]
Correct.  Which will stop the window from showing up.  Otherwise, use the `-dont_show` flag.

**Comment by sabinajashir** [comment]
thanks much. its working!!

**Comment by KfirdausMT** [comment]
Hi Sir @stephanecharette. Do you know how to mute the labels in the prediction window? I just want it to display the box without the labels name and score

**Comment by stephanecharette** [comment]
I suggest you use the API instead of the CLI.  Then you can make it do whatever you want.

If you want a CLI with a bit more control than Darknet, I suggest DarkHelp.  There are options to control most of the things you see on this page:  https://www.ccoderun.ca/darkhelp/api/classDarkHelp_1_1Config.html#a5375febf9720868f76dafc476fd6e83d

Including "hide labels" https://www.ccoderun.ca/darkhelp/api/classDarkHelp_1_1Config.html#a3086f69df165e7be96cd909682b44c54 and "suppress labels" https://www.ccoderun.ca/darkhelp/api/classDarkHelp_1_1Config.html#a80ab823f043d6f14f90b20c21fafb3b0
