### ISSUE TITLE
Can I use yolov2 detect for small image with single object?

### ISSUE THREAD

**Issue by matakk** [AlexeyAB/darknet#83]
Hi ,I want to detect object in a small image (like  w=20,h=50 ), In this small image  maybe have a single object (like a person), I wa detect this user the haar before in my project. now I want to change the detect method to yolov2,  And the other purpose is to reduce  the detect time.
I just change the 416 to small size is not work.
Any can help! thank a lot!

**Comment by AlexeyAB** [comment]
@matakk Hi, what size of images do you use?
Object's width or height should be not less than 7% of image width or height, provided that you use 416x416 network size.

**Comment by zenvendof** [comment]
@matakk I think it would be difficult for even humans, check this out:

![test](https://cloud.githubusercontent.com/assets/902416/26272047/1e757a34-3d42-11e7-83ec-d97fe7ad72ab.png)

Now this is a sharp stock photo image we can see her, imagine grainy video or photos.  That's not a lot of information for the algorithm to process and the vision is of "low resolution" since the network can detect higher pixel numbers (e.g. 416x416).  

In my opinion for some uses, traditional expert algorithms can still yield fantastic results:

http://funvision.blogspot.sg/2016/03/opencv-31-pedestrian-people-detection.html

Hear can run real time as well.

**Comment by AlexeyAB** [comment]
@matakk If you want to detect small objects (80x80) on the small images (80x80), then:

* you can use Tiny-Yolo `tiny-yolo-voc.cfg`: https://github.com/AlexeyAB/darknet/blob/b585124e55fcd18a7511d3b2fdc6bc3db5368ef4/cfg/tiny-yolo-voc.cfg

* then set `width=80` and `height=80` in the  `tiny-yolo-voc.cfg`

* And train your own network on your custom objects
