### ISSUE TITLE
How to save list of images that have detected objects.

### ISSUE THREAD

**Issue by AdrienT318** [AlexeyAB/darknet#8575]
Hi, I have ran object detection on a list of images using Yolov4 and have output the results of the bboxes to a JSON file.

What I need to do is save each image to a new folder with a bbox around the detected object. Any ideas?

Performing object detection on single images creates a predction.png image that is overwritten on each subsequent detection.

Thanks!

**Comment by stephanecharette** [comment]
Three different ideas:

1) Use the Darknet API.
2) Use OpenCV.
3) Use [DarkHelp Server](https://www.ccoderun.ca/darkhelp/api/Server.html).

**Comment by stephanecharette** [comment]
You need to check your footer when you post on a forum like this. :(

Use the API instead of the CLI.  It is simple.  For example:  https://www.ccoderun.ca/darkhelp/api/API.html

If you are not a software developer and cannot use the API, then my next suggestion is to use DarkHelp Server.  I provided a link to it in the previous comment.

**Comment by AdrienT318** [comment]
Thanks!

**Comment by AdrienT318** [comment]
Hey Stephane, I found another solution here > https://github.com/pjreddie/darknet/issues/903#issuecomment-709400840.

This provides images with bboxes in yoloV4, thought I'd share as I know you are very active here.
