### ISSUE TITLE
How to calculate object size yolov3 can detect, given a set of anchors.

### ISSUE THREAD

**Issue by panda9095** [AlexeyAB/darknet#859]
Hi, 

I am training a one-class detector on my own dataset. 
The objects sizes vary from 1.12 * 0.25 to 98 * 200. 

* I am wondering whether the yolov3 can detect such small object. In other words, how to calculate the range of object size the yolov3 can detect, given a set of anchors and the corresponding yolo-layer?

* In the output of training process, "Region 82 Avg IOU: -nan ... count: 0" occurs a lot. Should I remove the first yolo-layer? 
* If I would like to reduce the anchor number from 9 to say 5, how to arrange these anchors over the 3 yolo-layers ?

Cfg info:
* Image size and network size are both 416.
* Using calc_anchors generates the following anchors: 4,9,  6,15,  9,22,  13,29,  17,39,  22,50,  28,65,  42,94,  72,169. 
* Filter number before yolo-layer is 18.
* Other config remain unchanged.

Thx.

**Comment by AlexeyAB** [comment]
> The objects sizes vary from 1.12 * 0.25 to 98 * 200.

* Are these sizes of objects after that image has been resized to 416x416?

* Yolo can't detect object that less than 1 pixel - because it is absent on the image, so it can't be detected `1.12 * 0.25`. You should increase network resolution (increase height 4x times to 1664 instead of 416) to detect such objects.

> In the output of training process, "Region 82 Avg IOU: -nan ... count: 0" occurs a lot. Should I remove the first yolo-layer?

No.

> If I would like to reduce the anchor number from 9 to say 5, how to arrange these anchors over the 3 yolo-layers ?

As you want. 
Optimal size of object (and optimal anchors) for:

* **yolo Region 82** - 32x32 pixels (up to ~886x886 pixels) https://github.com/AlexeyAB/darknet/blob/4403e71b330b42d3cda1e0721fb645cf41bac14f/cfg/yolov3.cfg#L607

* **yolo Region 94** - 16x16 pixels (up to ~450x450 pixels) https://github.com/AlexeyAB/darknet/blob/4403e71b330b42d3cda1e0721fb645cf41bac14f/cfg/yolov3.cfg#L693

* **yolo Region 106** - 8x8 pixels (up to ~230x230 pixels) https://github.com/AlexeyAB/darknet/blob/4403e71b330b42d3cda1e0721fb645cf41bac14f/cfg/yolov3.cfg#L780
