### ISSUE TITLE
how to get prediction frame pics from the video "demo" command?

### ISSUE THREAD

**Issue by fjutsisejc** [AlexeyAB/darknet#860]
@AlexeyAB 
When I run "darknet detector demo **.mp4 -i 0 -out_filename **.mp4", how to get the picture frames with BB? 
modify the image.c? how?

**Comment by AlexeyAB** [comment]
Update your code from GitHub to use flag `-prefix filename`
And run such command:
`./darknet detector demo data/coco.data yolov3.cfg yolov3.weights -i 0 test.mp4 -prefix img`

you will see many files such as `img_1.jpg, img_2.jpg, ...`

**Comment by fjutsisejc** [comment]
Thank you for your reply!
By the way, can I output mp4 file when output img?

**Comment by AlexeyAB** [comment]
Yes, it just willn't show video on the screen, but it will save images and videofile:
`./darknet detector demo data/coco.data yolov3.cfg yolov3.weights -i 0 test.mp4 -prefix img -out_filename result.mp4`

**Comment by fjutsisejc** [comment]
@AlexeyAB 
I update the codes and rebuild. Run :./darknet detector demo data/coco.data yolov3.cfg yolov3.weights -i 0 test.mp4 -prefix img -out_filename result.mp4
I can see the mp4 file but I can't find any images . Why?

**Comment by AlexeyAB** [comment]
@fjutsisejc Yes, just use:
`./darknet detector demo data/coco.data cfg/yolov2.cfg yolov2.weights test.mp4 -prefix result_img/img`

**Comment by crystinaa** [comment]
@AlexeyAB 
can i get output mp4 file when output img with video on the screen

**Comment by fjutsisejc** [comment]
@crystinaa 
./darknet detector demo data/coco.data cfg/yolov2.cfg yolov2.weights test.mp4 -prefix result_img/img
it will output your mp4 and images.

**Comment by crystinaa** [comment]
@fjutsisejc 
its not working. just saving the output frames but not getting any detected output video on screen

**Comment by AlexeyAB** [comment]
@crystinaa 
Do you want so that it happens simultaneously:
* show video on the screen
* save video to the file
* save images with cropped objects?

1. Create directory `/result_img/` near with `./darknet`
2. Uncomment these lines: https://github.com/AlexeyAB/darknet/blob/04c0c4fdf84bb7b9e89604e8b9a6079016d5968c/src/image.c#L519-L534
3. Run this command:
`./darknet detector demo data/coco.data cfg/yolov3.cfg yolov3.weights test.mp4 -out_filename res.avi`

----

Or do you want so that it happens simultaneously:
* show video on the screen
* save video to the file
* save whole frames as images with bounded boxes?

1. Create directory `/result_img/` near with `./darknet`

2. change this line to this `if(!dont_show){ ` https://github.com/AlexeyAB/darknet/blob/04c0c4fdf84bb7b9e89604e8b9a6079016d5968c/src/demo.c#L209

3. Comment these 3 lines:
    * https://github.com/AlexeyAB/darknet/blob/04c0c4fdf84bb7b9e89604e8b9a6079016d5968c/src/demo.c#L241
    * https://github.com/AlexeyAB/darknet/blob/04c0c4fdf84bb7b9e89604e8b9a6079016d5968c/src/demo.c#L256
    * https://github.com/AlexeyAB/darknet/blob/04c0c4fdf84bb7b9e89604e8b9a6079016d5968c/src/demo.c#L261

4. Run this command:

`./darknet detector demo data/coco.data cfg/yolov4.cfg yolov4.weights test.mp4 -prefix result_img/img -out_filename res.avi`

**Comment by crystinaa** [comment]
@AlexeyAB 
thanks... it worked
