### ISSUE TITLE
How to update trained network?

### ISSUE THREAD

**Issue by brucefay1115** [AlexeyAB/darknet#8633]
I have already trained 100 images, if I add 10 images now, how to continue training through last.weights?

**Comment by EyGy** [comment]
Just add the new images to your train.txt and folder. When calling the train command now use you last.weights instead of the pre-trained .conv file you used before.

Then you can use the -clear flag to start from epoch 0 again or just add more epochs in you cfg. It will continue training on your weights then

Also you should really read the documentation more carefully, since this issue (and many more you will probably encounter) is covered there in detail.

**Comment by brucefay1115** [comment]
Got it! Thank you very much for your reply!
