### ISSUE TITLE
add or remove new class

### ISSUE THREAD

**Issue by zpmmehrdad** [AlexeyAB/darknet#88]
hi guys
how can i add or remove in the weights file? and i want to add positive images to my training weights file for improve it?

**Comment by AlexeyAB** [comment]
@zpmmehrdad Hi,

There is no simple way to do this. You should train from the beginning - with new images, number of class and number of filters in the cfg-file: https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

----

Some details:

* To delete classes - You can remove some parameters of some classes from weights, but this does not make sense, because reduces weights-file size and increases performance by less than 1%. Also it could be difficult for you to do it.

* To add classes - Even if you try to add new class, you should train this weights-file more, by using images of new class, so:

    * if you use dataset with content (old images + new images), then old classes will be overfited, but new class will not be sufficiently trained.
    * if you use dataset with content (only new images), then convolutional weights in your weights-file will be strongly adapted to the new class, but will become much worse to discover old classes.

In all cases, detection will be worse than if you train from the very beginning.
