### ISSUE TITLE
Using yolo DLL for new Visual Studio project

### ISSUE THREAD

**Issue by phongnhhn92** [AlexeyAB/darknet#90]
Hello guys, I managed to train my own model for detect custom objects and successfully run detection using YOLO DLL. However, i want to extend it more by applying to a new project on VS 2015. Would you mind telling me what should I do to use YOLO DLL for my new project ? 
Thanks so much !

**Comment by AlexeyAB** [comment]
@phongnhhn92 Hi,

Just required:
* `#include "yolo_v2_class.hpp"`
* add file `yolo_cpp_dll.lib` to your project - move it by mouse from folder to MSVS-window near with your cpp-files
* and put `yolo_cpp_dll.dll` to two places: near with exe-file and near with sln-file.

**Comment by phongnhhn92** [comment]
Thanks, using your suggestion I made a detection program using weights I just trained.
However, I intend to run this detector for Linux environment. Is it possible to use these lib and dll files for Linux. If it doesn't then, would you please give me some suggestion ?

**Comment by AlexeyAB** [comment]
@phongnhhn92 On Linux you should compile and use `.so`-library instead of `.dll`: https://stackoverflow.com/questions/14884126/build-so-file-from-c-file-using-gcc-command-line

More deteails:
* http://www.yolinux.com/TUTORIALS/LibraryArchives-StaticAndDynamic.html
* http://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html
