### ISSUE TITLE
Random 1 never works on my dataset !

### ISSUE THREAD

**Issue by ashuezy** [AlexeyAB/darknet#919]
![image](https://user-images.githubusercontent.com/31314950/40611314-75b11bce-6293-11e8-88d8-e8d0416ee4d3.png)
------
*updated today using- git pull origin master
*Makefile with random 1 or random 0
GPU=1
CUDNN=1
CUDNN_HALF=1
OPENCV=1
AVX=1
OPENMP=1
LIBSO=0

Segmentation fault      (core dumped)

*Tried with this Makefile with random 1
GPU=1
CUDNN=1
CUDNN_HALF=0
OPENCV=1
AVX=0
OPENMP=0
LIBSO=0

Got Nan
---------------------------------------------

Only configuration that works !
*Tried with this Makefile with random 0
GPU=1
CUDNN=1
CUDNN_HALF=0
OPENCV=1
AVX=0
OPENMP=0
LIBSO=0

**Comment by AlexeyAB** [comment]
* What GPU do you use?
* If you train with `CUDNN_HALF=0`, did you get nan in the avg loss?
* What width and height in your cfg-file?

**Comment by ashuezy** [comment]
GPU is Gtx 1080 ti
With CUDNN_HALF i always get Nan

**Comment by AlexeyAB** [comment]
@ashuezy 
There were some incorrect labels in your txt files.
I fixed source code, so now it just rejects incorrect labels with attention message `Wrong annotation: x = %f, y = %f`, without seg-fault errors. I tested with your dataset and it can be trained **at least 750 iterations.**
Update your source code from GitHub.

![image](https://user-images.githubusercontent.com/4096485/40627834-f0c1c5c6-62c9-11e8-9c62-a6f6b5d7e4cf.png)

**Comment by ashuezy** [comment]
@AlexeyAB 
Thanks..

Would i be able to see which file contains wrong labels ?

**Comment by AlexeyAB** [comment]
> b73e03a3-c09c-4710-a5bb-b0befeb43fd4.txt ?
> 
> > 0 **0.0 0.0** 0.0044444444444444444 0.006779661016949152
> > 0 0.08071537111111111 0.45941490508474575 0.02411044444444444 0.06665643389830511
> > 0 0.11967657777777778 0.47215723389830505 0.026507773333333328 0.064340813559322
> > 0 0.16463824222222223 0.49176192203389835 0.029984715555555555 0.06524659661016952
> > 0 0.20622222222222222 0.5026741966101694 0.02812097333333333 0.07187852203389827
> > 0 0.4957401311111111 0.24349978305084746 0.20804909777777772 0.4824045423728812
> > 0 0.8607812488888891 0.9206302949152542 0.07554297333333339 0.17084342372881364
> 
> But when i see it in Yolo_Mark tool I am able to correctly see 6 tags and the first one is ignored ?


You see 6 labels, but in the txt-file there are 7 labels.

1st label has coordinate `x=0 y=0` - it was wrong for Yolo. 
I fixed it, so now these incorrect labels will be ignored automatically without any errors.

----

Also, if you press SPACE button in the Yolo_mark when you see this image with wrong label, then wrong labels will be removed. So you can just hold SPACE button, to pass through all images and to clean up your dataset. But now it isn't necessary for this fork, due to my fix.

* Wrong label:

![image](https://user-images.githubusercontent.com/4096485/40657014-00b04b94-634f-11e8-9cce-1e1c5621e957.png)

* After SPACE button has been pressed:

![image](https://user-images.githubusercontent.com/4096485/40657049-1a78551c-634f-11e8-9114-7936acaae514.png)

**Comment by ashuezy** [comment]
@AlexeyAB 
Your so awesome !
